hmcts/div-case-orchestration-service

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationController.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/TestConstants.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/DeleteDraftTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/EmailNotificationTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RetrieveDraftTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SaveToDraftStoreTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DeleteDraftWorkflowTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/RetrieveDraftWorkflowTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SaveDraftWorkflowTest.java
Added unit test for draft store workflow.
* Hardware:
* JDK:
=> DIV-3211 Added unit test for draft workflow

build.gradle, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
Use the AosLetterHolderId as key name instead of respondentLetterHolderId
=> [PREVIEW] Use correct key name for Respodent Letter Holder ID

README.md
* Added Lombok/Annotation Processing instructions for Intellij IDEA
* Updated running instructions to use bootRun
* Updated incorrect port number for the app/Swagger link
Fixes DIV-3264
Documentation update
=> [PREVIEW] DIV-3264 - Updated build/run instructions in README.md

infrastructure/main.tf
=> Add DraftCheckCCD to the environment variables

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/RootController.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/RootControllerTest.java
Add a root controller to avoid the 404 errors being returned by Azure
=> [PREVIEW] Add root controller

Dockerfile, Jenkinsfile_CNP, infrastructure/output.tf, src/kubernetes/config.aat.yaml, src/kubernetes/deployment.template.yaml, src/main/resources/application.yml
=> enable aks on build pipeline

src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/RetrieveAosTest.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/helper/GlobalExceptionHandler.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/exception/CaseNotFoundException.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RetrieveAosCase.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/helper/GlobalExceptionHandlerUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RetrieveAosCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RetrieveAosCaseUTest.java
404 when there are no case
* Hardware:
* JDK:
=> [PREVIEW] Throw exception when there are no case

src/integrationTest/resources/fixtures/maintenance/submit-aos/aos-defend-consent.json, src/integrationTest/resources/fixtures/maintenance/submit-aos/aos-defend-no-consent.json, src/integrationTest/resources/fixtures/maintenance/submit-aos/aos-no-defend-consent.json, src/integrationTest/resources/fixtures/maintenance/submit-aos/aos-no-defend-no-consent.json
Fix RespAgreeCosts answer fixes per config
* Hardware:
* JDK:
=> change the answer to RespAgreeToCosts

src/kubernetes/deployment.template.yaml
=> update to use traefik ingress

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/PetitionIssueTest.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetIssueDate.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CcdCallbackWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/PetitionIssuedITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetIssueDateTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CcdCallbackWorkflowTest.java
To be displayed on the mini petition on DN/AOS
Fixes #3321
=> DIV-3321 - set issue date on CCD callback

infrastructure/main.tf, infrastructure/variables.tf
=> Add app insights

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetCourtDetails.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetIssueDate.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateRespondentDetails.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/CcdUtil.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/LinkRespondentIdamITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/PetitionIssuedITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SolicitorCreateITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetCourtDetailsTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetIssueDateTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateRespondentDetailsUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/util/CcdUtilUTest.java
Set ReceivedAOSfromResp and ReceivedAOSfromRespDate on linking
* Hardware:
* JDK:
=> Set ReceivedAOSfromResp and ReceivedAOSfromRespDate on linking

src/integrationTest/resources/fixtures/maintenance/submit-aos/aos-defend-consent.json, src/integrationTest/resources/fixtures/maintenance/submit-aos/aos-defend-no-consent.json, src/integrationTest/resources/fixtures/maintenance/submit-aos/aos-no-defend-consent.json, src/integrationTest/resources/fixtures/maintenance/submit-aos/aos-no-defend-no-consent.json
Fixing text fixtures for changes made to CCD config 
* Hardware:
* JDK:
=> Fix text fixtures

src/integrationTest/resources/fixtures/maintenance/submit-aos/aos-defend-consent.json, src/integrationTest/resources/fixtures/maintenance/submit-aos/aos-defend-no-consent.json, src/integrationTest/resources/fixtures/maintenance/submit-aos/aos-no-defend-consent.json, src/integrationTest/resources/fixtures/maintenance/submit-aos/aos-no-defend-no-consent.json
=> Sync demo with master

src/integrationTest/java/uk/gov/hmcts/reform/divorce/draft/DraftServiceEndToEndTest.java, src/integrationTest/resources/draft/complete-case-response.json, src/integrationTest/resources/fixtures/retrieve-aos-case/aos-divorce-session.json
Added Created date in session data
Fixes # DIV-3493
* Hardware:
* JDK:
=> Added Created date in session data

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/PetitionIssueCallBackE2ETest.java
Removed unused test event
* Hardware:
* JDK:
=> Removed unused test event  testIssuedPetitionCOS

build.gradle, dependency-check-suppressions.xml
Bump up guava dependency to fix security scan
* Hardware:
* JDK:
=> Temporal exclusion of guava on dependency scan

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/PetitionIssueTest.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
Change document type to aos.
* Hardware:
* JDK:
=> document type AOS

src/integrationTest/java/uk/gov/hmcts/reform/divorce/draft/DraftServiceEndToEndTest.java
Delete draft fixes
* Hardware:
* JDK:
=> delete all code

src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/LinkRespondentTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/RetrieveCaseTest.java, src/integrationTest/resources/application.properties, src/integrationTest/resources/fixtures/retrieve-case/divorce-session.json, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/OrchestrationServiceApplication.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseMaintenanceClient.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/ccd/FeeValue.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/GetCase.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/GetCaseWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/LinkRespondentIdamITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RetrieveCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/GetCaseUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CcdCallbackBulkPrintWorkflowTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/GetCaseWorkflowUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/LinkRespondentWorkflowUTest.java
Retrieve Case Endpoint
* Hardware:
* JDK:
=> added a new endpoint to retrieve cases

src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/LinkRespondentTest.java
=> Ingored failed test

src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/SubmitAosCaseTest.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitAosCase.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitAosCaseUTest.java
Progress case to AwaitingDecreeNisi the "proceed but don't admit" option
Fixes #DIV-3710
* Hardware:
* JDK:
=> DIV-3710 - changed unreasonable behaviour event for consent/no admit

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/BulkPrintCallbackTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/IntegrationTest.java, src/main/resources/application.yml
=> Due date chagnes div3732

src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/IntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/LinkRespondentTest.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateRespondentDetails.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateRespondentDetailsUTest.java
Added startAosFromOverdue and  reissueFromOverdue events that allows the respondent get access to the case once the case is on AosOverdue.
* Hardware:
* JDK:
=> DIV-3725 Allow Aos start from aosOverdue

checkstyle.xml, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/LinkRespondentTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/SubmitAosCaseTest.java, src/integrationTest/resources/application.properties, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitAosCase.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateRespondentDetails.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/LinkRespondentIdamITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SubmitAosCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitAosCaseUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateRespondentDetailsUTest.java, src/test/resources/application.yml
As we've recently changed the initial dueDate to 30 days, we don't need
modify the due date on submission/linking case
Fixes #DIV-3759
=> DIV-3759 - don't change dueDate

build.gradle, dependency-check-suppressions.xml
This is temporal solution to unblock the pipeline
There is a story to proper fix this DIV-3817
* Hardware:
* JDK:
=> Ignore  issue slf4j

build.gradle, dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateRespondentDetails.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/LinkRespondentIdamITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateRespondentDetailsUTest.java
AoS fetching is more flexible with Case States so we can switch to using it directly when linking.
Supporting the equivalent change in CMS: https://github.com/hmcts/div-case-maintenance-service/pull/46
Story description DIV-3479
* Hardware:
* JDK:
=> Update tests to handle new AoS fetching + filtering

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseMaintenanceClient.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/PopulateExistingCollections.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/UpdateToCCDWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/UpdateCaseTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/PopulateExistingCollectionsUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/UpdateToCCDWorkflowTest.java
=> Populate existing payments before updating

src/integrationTest/resources/draft/draft-part1-response.json, src/integrationTest/resources/draft/draft-part1.json, src/integrationTest/resources/draft/draft-with-divorce-format.json, src/integrationTest/resources/draft/save-draft.json, src/integrationTest/resources/fixtures/issue-petition/ccd-callback-aos-invitation-service-centre.json, src/integrationTest/resources/fixtures/issue-petition/ccd-callback-aos-invitation.json, src/integrationTest/resources/fixtures/issue-petition/submit-complete-case.json, src/integrationTest/resources/fixtures/issue-petition/submit-unlinked-case.json, src/integrationTest/resources/fixtures/maintenance/update/submit-case-data.json, src/integrationTest/resources/fixtures/retrieve-aos-case/aos-divorce-session.json, src/integrationTest/resources/fixtures/retrieve-case/divorce-session.json, src/integrationTest/resources/fixtures/solicitor/ccd-request-data.json, src/integrationTest/resources/fixtures/solicitor/solicitor-request-data.json
https://tools.hmcts.net/jira/browse/DIV-3830
Replaced instances of email@email.com with proper gov notify simulate-delivered email
=> DIV-3830: Replaced invalid emails with proper gov-notify one

src/kubernetes/config.aat.yaml
=> DIV-3840 - Changed CFS URL back to AAT

src/integrationTest/resources/fixtures/maintenance/submit-dn/dn-submit.json
- Amended test data to send new hasBenChanges field in the integration
tests.
Enhanced the test data for integration test so the hasBeenChanges field is sent to CCD.
https://tools.hmcts.net/jira/browse/DIV-3855
=> Send hasBeenChanges session data to CCD

dependency-check-suppressions.xml
No longer affected
Fixes #DIV-3814 
Pipeline checks
=> DIV-3814 - removed dependency check suppression

src/integrationTest/resources/draft/complete-case-response.json, src/integrationTest/resources/draft/complete-petition-draft.json, src/integrationTest/resources/fixtures/retrieve-aos-case/aos-divorce-session.json, src/integrationTest/resources/fixtures/retrieve-case/divorce-session.json, src/main/resources/application.yml, src/test/resources/application.yml
=> Changed to new divorcecase court email

build.gradle, dependency-check-suppressions.xml
=> DIV-4018: Supressed dependencies, updated dependencyAnalyze version

Jenkinsfile_nightly, security.sh
=> set up divorce cos security scan

build.gradle
CVE-2019-7722
* Hardware:
* JDK:
=> Upgrade PMD to fix CVE-2019-7722

src/integrationTest/java/uk/gov/hmcts/reform/divorce/draft/DraftServiceEndToEndTest.java, src/integrationTest/resources/draft/complete-case-response.json
=> Fix broken build

src/integrationTest/resources/fixtures/maintenance/co-respondent/co-respondent-answers.json
- Aos and Answer node are no longer submitted by front end.
* Hardware:
* JDK:
=> Fixed broken tests.

src/integrationTest/resources/fixtures/maintenance/co-respondent/co-respondent-answers.json, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/config/courtallocation/DivorceCasesRatio.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/courts/CourtEnum.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/config/courtallocation/CourtAllocationConfiguratorIntegrationTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/courtallocation/CourtAllocatorITest.java, src/test/resources/application.yml
Routed desertion cases to CTSC
Refactored some court allocation test
* Hardware:
* JDK:
=> [PREVIEW] DIV-4357 Routed desertion to CTSC

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/BulkPrintCallbackTest.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/BulkPrinter.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/BulkPrintTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/BulkPrinterTest.java
bulk print co-respondent letter
https://tools.hmcts.net/jira/browse/DIV-4270
Unit tests only. Will require manual QA test with bulk print team.
=> DIV-4270 bulk print co-respondent letter

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/AosReceivedCallbackTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/AosSubmittedCallbackTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/CoRespReceivedCallbackTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/DNReceivedTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/IntegrationTest.java, src/integrationTest/resources/fixtures/co-resp-case/co-resp-defend.json, src/integrationTest/resources/fixtures/co-resp-case/co-resp-undefend.json, src/integrationTest/resources/fixtures/respond-to-a-divorce/ccd-callback-aos-submitted.json, src/integrationTest/resources/fixtures/retrieve-aos-case/aos-received.json, src/integrationTest/resources/fixtures/submit-dn/dn-submitted.json, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/GenericEmailNotification.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/RespondentSubmittedCallbackWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/RespondentSubmittedCallbackWorkflowUTest.java
Fixes email not sending if any of the people have accent in their names, updating to new version fixes it, most probably the latest release 3.14.1-RELEASE introduced the fix, all working now.
Ticket: https://tools.hmcts.net/jira/browse/DIV-4460
* Hardware:
* JDK:
=> DIV-4460 - fix email encoding errors

src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/LinkRespondentTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/SubmitRespondentAosCaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/CcdSubmissionSupport.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitCoRespondentAosCase.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitRespondentAosCase.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateRespondentDetails.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/LinkRespondentIdamITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SubmitCoRespondentAosCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SubmitRespondentAosCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitCoRespondentAosCaseUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitRespondentAosCaseUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateRespondentDetailsUTest.java
Combined stories DIV-4446 and DIV-4447 
DIV-4446 
DIV-4447 
* Hardware:
* JDK:
=> DIV-4446 Set ReceivedAos on AOS submit

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/DefaultWorkflow.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/task/DefaultTaskContext.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/task/TaskContext.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/task/DefaultTaskContextTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/BulkPrinterTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/GetInconsistentPaymentInfoUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/ValidateCaseDataTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/ValidateSolicitorCaseDataTest.java
-Renamed the variable to something more sensible.
* Hardware:
* JDK:
=> Refactor - Code cleanup

src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/SubmitCoRespondentAosCaseTest.java
=> Test branch

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java
- Rename of method
* Hardware:
* JDK:
=> Refator - rename method name

src/integrationTest/resources/fixtures/amend-petition/issued-case.json
Updates the JSON used in ITest to match PFE submitted. Allows for better integration testing.
=> DIV-4399 Update JSON to latest petition submission from PFE (CCD)

dependency-check-suppressions.xml, infrastructure/prod.tfvars
=> Enable SIDAM on Prod

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/PetitionIssueTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/AmendPetitionTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/LinkRespondentTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/SubmitCoRespondentAosCaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/SubmitRespondentAosCaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cos/CosApiClient.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cos/DraftsSubmissionSupport.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/util/DateConstants.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/util/ResourceLoader.java, src/integrationTest/resources/fixtures/amend-petition/issued-case.json, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationController.java
Integration test to make sure that the issueDate from the original case is copied to the amended case.
=> DIV-4531: Integration tests

src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/RetrieveCaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/CcdClientSupport.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/EmailService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SendRespondentSubmissionNotificationWorkflow.java
Improving logs for support investigations.
=> DIV-4663: Improving logs for support investigations.

src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/RetrieveAosTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/RetrieveCaseTest.java, src/integrationTest/resources/draft/complete-case-response.json, src/integrationTest/resources/draft/complete-petition-draft.json, src/integrationTest/resources/fixtures/issue-petition/submit-complete-case.json, src/integrationTest/resources/fixtures/retrieve-aos-case/aos-divorce-session.json, src/integrationTest/resources/fixtures/retrieve-case/divorce-session.json, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/courts/CourtEnum.java, src/main/resources/application.yml, src/test/resources/application.yml
https://tools.hmcts.net/jira/browse/DIV-4580
Updated CTSC site id : AA07
* Hardware:
* JDK:
=> Set ctsc site id as AA07

src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/LinkRespondentTest.java
For non-existent case ID
Fixes # DIV-4679
=> DIV-4679 - update integration test to expect UNAUTHORISED

charts/div-cos/values.aat.template.yaml, charts/div-cos/values.preview.template.yaml, infrastructure/main.tf, infrastructure/output.tf, infrastructure/variables.tf, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerUpdateNotificationsEmail.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerNotificationEmailTest.java, src/test/resources/application.yml
[DIV-4218](https://tools.hmcts.net/jira/browse/DIV-4218)
Removes unnecessary feature toggles.
=> Removed feature toggles

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/CoRespondentReceivedCallbackTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cos/CosApiClient.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetCoRespondentAnswerReceived.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CoRespondentAnswerReceivedWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/CoRespondentAnswerReceivedITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetCoRespondentAnswerReceivedTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CoRespondentAnswerReceivedWorkflowUTest.java
https://tools.hmcts.net/jira/browse/DIV-4602
Added callback to set answer received from co-respondent fields
DIV-4602
* Hardware:
* JDK:
=> DIV-4602 Added Co-respondent answer received callback

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java
[DIV_4680 - PciPal](https://tools.hmcts.net/jira/browse/DIV-4680)
This will mainly be manual caseworker reconciliation. This PR changes simply allows the payment service to pass in a channel of payment instead of always storing it as "online".
* Hardware:
* JDK:
=> pci-pay changes

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/IntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/IdamUtils.java
Retry 5 times, with 200 ms in between each retry in the case of failures
Fixes #pipeline
=> Attempt to fix IDAM issue where recently created user is not recognised

Jenkinsfile_CNP, infrastructure/demo.tfvars, infrastructure/sandbox.tfvars, infrastructure/sprod.tfvars, infrastructure/variables.tf
TIDAM is deprecated, pointing all env to SIDAM instead.
=> Point to SIDAM

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/CoRespondentGenerateAnswersTest.java, src/integrationTest/resources/application.properties, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CoRespondentAnswersGenerator.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/GenerateCoRespondentAnswersWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/GenerateCoRespondentAnswersITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CoRespondentAnswersGeneratorTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/GenerateCoRespondentAnswersWorkflowTest.java
[DIV-4538](https://tools.hmcts.net/jira/browse/DIV-4538)
This adds a COS endpoint which can be called via a CCD callback to generate the Co-Respondent answers and append them to the D8DocumentsGenerated data field.
* Hardware:
* JDK:
=> Add Co-RespondentAnswers Generator and relevant tests

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/DocumentGenerationTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DocumentGenerationWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DocumentGenerationITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/DocumentGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DocumentGenerationWorkflowTest.java
- The majority (if not all) of our request to COS for document
generation follow the same pattern. We call DGS with a bunch of
parameters and the case data. We seem to repeat this practice
every time we need to introduce a new document.
This PR aims to generalise document generation and attachment to
a case. CCD configuration will be required where we need a callback
to generate a new document.
Three request parameters will be pased in:
*templateId - the unique identifier for the document template
*documentType - the document type for CCD tracking
*filename - the output filename (note this is just a prefix and will
get concatenated with the case Id)
A typical callback:
```
/generate-document?templateId=divorceminipetition&documentType=petition&filename=d8petition
```
Please include a …
=> DIV-4895 Generic document generation

build.gradle, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/ProcessBulkCaseITest.java
Fix async test
* Hardware:
* JDK:
=> Fix async test

src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/CreateBulkCaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/CcdClientSupport.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/CcdSubmissionSupport.java
=> Add await on integration test

src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/CcdSubmissionSupport.java
Fix checkstyle issue
* Hardware:
* JDK:
=> Fix checkstyle

lib/AI-Agent.xml, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/job/CreateBulkCaseJob.java
Added log to see clearly when the schedule is triggered and appInsight instrumetation.
* Hardware:
* JDK:
=> Added log on CreateBulkCaseJob and AppInsight instrumentation

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/job/CreateBulkCaseJob.java
Added default constructor for job needed by quartz
* Hardware:
* JDK:
=> Keep default constructor for quartz

src/integrationTest/resources/fixtures/maintenance/submit-aos/aos-solicitor-representation.json, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/ccd/CoreCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitRespondentAosCase.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SubmitRespondentAosCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitRespondentAosCaseUTest.java, src/test/resources/jsonExamples/payloads/aosSolicitorNominated.json
https://tools.hmcts.net/jira/browse/DIV-4966
Mapping moved from D8RespondentCorrespondenceSendToSol to respondentSolicitorRepresented
=> Mapping moved from D8RespondentCorrespondenceSendToSol 

charts/div-cos/values.aat.template.yaml, charts/div-cos/values.preview.template.yaml, infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/output.tf, infrastructure/variables.tf, job-scheduler/src/main/java/uk/gov/hmcts/reform/divorce/scheduler/service/CronJobScheduler.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/CreateBulkCaseTest.java, src/main/resources/application.yml
1.  Added log to troubleshoot schedule 
2. Disabled create bulk case scheduler on AKS
3. Override schedule cron to run every 30 mins on aat
4. Disable Create Bulk case integration test(Requested by QA's) I will take them back after manual testing
* Hardware:
* JDK:
=> Log schedule cron

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/EmailService.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/EmailServiceTest.java
Fix Prod bug causing exception when saving draft and sending email verification.
=> Fix email service to use template name and not ID

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetSeparationFields.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetSeparationFieldsTest.java
https://tools.hmcts.net/jira/browse/DIV-4704
=> Change in sep ref date logic

charts/div-cos/values.preview.template.yaml, src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/PetitionIssueTest.java, src/integrationTest/resources/fixtures/issue-petition/ccd-callback-aos-invitation-east-midlands.json, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/IssueEventWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/PetitionIssuedITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/IssueEventWorkflowTest.java
Nottingham RDC staff to be able to progress solicitor cases online
Effectively means allowing them to generate the AoS Pack - they will be given the `_beta` role to allow access to CTSC case events.
https://tools.hmcts.net/jira/browse/DIV-4634
=> DIV-4634 Added clause to allow Nottingham staff access to AoS pack

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/config/DnCourtDetailsConfig.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/ccd/CaseDetails.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/courts/DnCourt.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CourtLookupService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/DocumentGenerationTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetFormattedDnCourtDetails.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/TaskCommons.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DocumentGenerationWorkflow.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/courts/DnCourtTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DocumentGenerationITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CourtLookupServiceTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/DocumentGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetFormattedDnCourtDetailsTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/util/TaskCommonsTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DocumentGenerationWorkflowTest.java, src/test/resources/application.yml
[DIV-4942-DN-Court-Details](https://tools.hmcts.net/jira/browse/DIV-4942)
This PR adds the formatted court details to be sent to DGS, without affecting actual case data.
Automated Tests. Will point PR to DGS AAT and test through Swagger for manual testing.
=> Add Court Contact Details to Document Generator Task

build.gradle, checkstyle.xml, src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/PaymentUpdateCallbackTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/RetrieveAosTest.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/FeatureToggleServiceClient.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/IdamClient.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/TacticalIdamClient.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/idam/Pin.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/idam/PinRequest.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SearchAwaitingPronouncementCases.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/AuthUtil.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/management/monitoring/health/WebServiceHealthCheckUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/ScheduleTestJobScheduleTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerSubmissionNotificationEmailTest.java
- OWASP upgraded to v5, fixed arising vulnerabilities in swagger and elasticsearch
- Checkstyle upgraded to 8.21 with an accompanying modification to the `checkstyle.xml` file
Fixes # [DIV-5053](https://tools.hmcts.net/jira/browse/DIV-5053)
=> DIV-5053: OWASP upgrade

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/BulkCaseCreate.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SearchAwaitingPronouncementCases.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/ProcessBulkCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/BulkCaseCreateUTest.java, src/test/resources/application.yml
Added minimum number of cases within a bulk case
https://tools.hmcts.net/jira/browse/DIV-4943
* Hardware:
* JDK:
=> Div 4943 add minimum cases

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/RetryableBulkCaseWorkflow.java
Refactor to make variable name more descriptive and caseId logging
* Hardware:
* JDK:
=> DIV-4825 Improve var names and log

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/BulkCaseConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/RetryableBulkCaseWorkflow.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/BulkCaseService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/BulkCaseServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SearchAwaitingPronouncementCases.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/RetryableBulkCaseWorkflowTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/ProcessBulkCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/BulkCaseServiceImplTest.java
Added new temporal state for bulk case creation to avoid process the bulk case when any case within the bulk fail on linking process
This PR needs this config https://github.com/hmcts/div-case-maintenance-service/pull/148
and this change con CMS
https://github.com/hmcts/div-case-maintenance-service/pull/148
https://tools.hmcts.net/jira/browse/DIV-5046
* Hardware:
* JDK:
=> Add new temporal state for bulk creation

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/ScheduleBulkCaseForListingTest.java, src/integrationTest/resources/application.properties
Fix integration test
* Hardware:
* JDK:
=> Fix integration test

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/UpdatePronouncementDateWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/UpdateBulkCaseDnPronouncementDateITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/UpdatePronouncementDateWorkflowTest.java
[DIV-4947](https://tools.hmcts.net/jira/browse/DIV-4947)
Automated testing
=> DIV-4947 Use new event for Bulk Case DN Pronouncement

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorSubmissionWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorSubmissionWorkflowTest.java
=> DIV-4977: renamed ProcessPbaPayment to SolicitorSubmission

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/AddDecreeNisiDecisionDateTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/BulkCaseCreate.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DecreeNisiAboutToBeGrantedWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DecreeNisiAboutToBeGrantedTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/AddDecreeNisiDecisionDateTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/BulkCaseCreateUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DecreeNisiAboutToBeGrantedWorkflowTest.java
DIV-5097 Add decision date when LA rejects DN
DIV-5097
* Hardware:
* JDK:
=> DIV-5097 Add decision date when LA rejects DN

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetSeparationFields.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetSeparationFieldsTest.java
Enforces a fixed date for the failing tests requiring use of LocalDate.now() / LocalDateTime.now()
=> Fixed Clock for tests requiring .now()

LICENSE.md, README.md
=> DIV-3264: Update readme

infrastructure/variables.tf
Enable schedule
https://tools.hmcts.net/jira/browse/DIV-5187
* Hardware:
* JDK:
=> DIV-5187 Enable schedule by default

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/courts/Court.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CourtLookupServiceTest.java
Adds care of prefix back in for serviceCentre address.
* Hardware:
* JDK:
=> Add Care of Prefix back in

src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/MakeCaseEligibleForDATest.java, src/integrationTest/resources/application.properties, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/MakeCaseEligibleForDecreeAbsoluteWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/MakeCaseEligibleForDATest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/MakeCaseEligibleForDecreeAbsoluteWorkflowTest.java
This is to be called by the job scheduler for every case in "DN Pronounced" as soon as its DN has been pronounced for 6 weeks + 1 day.
Integration, Functional and Unit tests.
=> DIV-5110: Creating endpoint to make a case eligible for DA

src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/MakeCaseEligibleForDATest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/MakeCaseEligibleForDAWorkflowTest.java, src/integrationTest/resources/application.properties, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/DecreeAbsoluteCaseInternalController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/event/listener/UpdateDNPronouncedCaseEventListener.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/task/AsyncTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/job/UpdateDNPronouncedCaseJob.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/DecreeAbsoluteService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/DecreeAbsoluteServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateDNPronouncedCase.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/UpdateDNPronouncedCasesWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/DecreeAbsoluteCaseInternalControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/job/UpdateDNPronouncedCaseJobTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/DecreeAbsoluteServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateDNPronouncedCaseTest.java
It passes, but I'm still working on a few things.
=> Jobscheduler DA fix

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/ValidateDNDecisionTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DecreeNisiAboutToBeGrantedWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DecreeNisiAboutToBeGrantedTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/ValidateDNDecisionTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DecreeNisiAboutToBeGrantedWorkflowTest.java
DIV-5193 BE validation on cost decision
* Hardware:
* JDK:
=> DIV-5193 Added validation on cost decision

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/ValidateDNDecisionTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/util/TaskUtils.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/ValidateDNDecisionTaskTest.java
Add null-safety on callback when the element in the payload is null
https://tools.hmcts.net/jira/browse/DIV-5292
* Hardware:
* JDK:
=> DIV-5292 Add null-safety on callback

infrastructure/aat.tfvars, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SearchAwaitingPronouncementCases.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SearchAwaitingPronouncementCasesTest.java
=> DIV-5237 set search order.

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/ProcessApplicantDAEligibilityCallbackTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cos/CosApiClient.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CalculateDecreeAbsoluteDates.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/util/TaskUtils.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/CcdUtil.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/DateUtils.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/decreeabsolute/ApplicantDecreeAbsoluteEligibilityWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/decreeabsolute/ProcessApplicantDAEligibilityTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CalculateDecreeAbsoluteDatesTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/util/TaskUtilsTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/util/CcdUtilUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/decreeabsolute/ApplicantDecreeAbsoluteEligibilityWorkflowTest.java
This calculates the DA-relates date we need when a case is considered to be "Eligible for DA".
=> DIV-5062: Calculating DA-related dates and returning them to CCD.

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SearchAwaitingPronouncementCases.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SearchAwaitingPronouncementCasesTest.java
JIRA Ticket
[DIV-5346](https://tools.hmcts.net/jira/browse/DIV-5346)
* Hardware:
* JDK:
=> Remove duplicates during the case search

build.gradle, dependency-check-suppressions.xml
Updated Owasp Dependencycheck to latest version. Removed unnecessary suppressions & added comments to remaining 2 suppressions explaining why they are suppressed
=> Bumped dependencycheck version and tidied up suppressions

infrastructure/preview.tfvars, infrastructure/variables.tf, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/management/config/SwaggerConfiguration.java
Updated swagger config using new version
* Hardware:
* JDK:
=> DIV-5194 Upgrade swagger config

infrastructure/prod.tfvars
To enable a scheduler job which makes cases eligible for Decree Absolute
Unit tests, integration tests, and full end2end tests in the AAT
search server logs with the following criterial 
-- "MakeCasesEligibleForDAJob executed"
=> enable the scheduler job MakeCasesEligibleForDA in production

src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/IntegrationTest.java
to reduced failed notification on gov notify
=> changeDomain

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/SolicitorLinkCaseCallbackTest.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendRespondentSolicitorAosInvitationEmail.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendRespondentSolicitorAosInvitationEmailTest.java
* Provided an override for the optional solicitor name field
* Also fixed solicitor link integration tests by properly overriding the fields
Fixes #DIV-4630
=> DIV-4630 - Fix solicitor link test and name callback

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitCoRespondentAosCase.java
=> Change all reference to DNAwaiting to AwaitingDecreeNisi

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/IssueAosPackOfflineTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cos/CosApiClient.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CaseFormatterAddDocuments.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/aospack/offline/IssueAosPackOfflineWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/aospack/offline/AosPackRespondentOfflineTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/aospack/offline/IssueAosPackOfflineWorkflowTest.java
=> DIV-5502: Writing integration tests now that DGS is ready

build.gradle, job-scheduler/build.gradle
=> Update Jackson-Databind to 2.9.9.3

src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/config/DnCourtDetailsConfigValidationTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetFormattedDnCourtDetailsTest.java, src/test/resources/application.yml
[DIV-5592](https://tools.hmcts.net/jira/browse/DIV-5592)
New DnCourt details.
* Hardware:
* JDK:
=> Added new court with details to DnCourt list

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/EditBulkCaseListingTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cos/CosApiClient.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkCaseController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/TestConstants.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkCaseControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/EditBulkCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java
Created callback combining Hearing date validation and Judge pronouncement  list document generation
* Hardware:
* JDK:
=> Div 4974 edit bulk case listed callback

src/integrationTest/resources/fixtures/case-linked-for-hearing/case-linked-for-hearing-error.json, src/integrationTest/resources/fixtures/case-linked-for-hearing/case-linked-for-hearing.json, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerCertificateOfEntitlementNotificationEmail.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendRespondentCertificateOfEntitlementNotificationEmail.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerCertificateOfEntitlementNotificationEmailTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendRespondentCertificateOfEntitlementNotificationEmailTest.java, src/test/resources/jsonExamples/payloads/caseListedForHearing.json, src/test/resources/jsonExamples/payloads/solCaseListedForHearing.json
[DIV-5593](https://tools.hmcts.net/jira/browse/DIV-5593)
This PR passes the CourtName parameter to the notification email. This field should be set by the case event that updates the current case and triggers this notification callback.
=> DIV-5593 Case Linked For Hearing Notification Update With Court Name

src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/IntegrationTest.java
Use predefined caseworker and solicitor  for test instead of create a new one per set
TEST_CASE_WORKER_USER@mailinator
TEST_SOLICITOR@mailinator.com
* Hardware:
* JDK:
=> Use fix caseworker and solicitor on test

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetDaRequestedDetailsTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/decreeabsolute/ApplicantDecreeAbsoluteEligibilityWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetDaGrantedDetailsTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetDaRequestedDetailsTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/decreeabsolute/ApplicantDecreeAbsoluteEligibilityWorkflowTest.java
Populate date field when daRequested
https://tools.hmcts.net/jira/browse/DIV-5602
=> DIV-5602 Populate date field when daRequested

src/integrationTest/java/uk/gov/hmcts/reform/divorce/dataextraction/FamilyManDataExtractionIT.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeAbsoluteDataExtractor.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DataExtractionFileCreatorTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeAbsoluteDataExtractorTest.java
=> Changing DN Pronouncement date logic after new decision from business

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/courts/DnCourt.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/courts/DnCourtTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DocumentGenerationITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CourtLookupServiceTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetFormattedDnCourtDetailsTest.java
For [DIV-5107](https://tools.hmcts.net/jira/browse/DIV-5107)
This should only be merged in after https://github.com/hmcts/div-document-generator-client/pull/162 has been merged.
Automated testing
=> Moved DGS Court Address Formatter to COS

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/event/listener/DataExtractionRequestListener.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/CSVExtractorFactory.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DataExtractionFileCreator.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/ExtractedDataPublisher.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/dataextraction/FamilyManDataExtractionWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/event/listener/DataExtractionRequestListenerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/CSVExtractorFactoryTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DataExtractionFileCreatorTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/ExtractedDataPublisherTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/dataextraction/FamilyManDataExtractionWorkflowTest.java
- [ x] New feature (non-breaking change which adds functionality)
Unit, functional and integration tests
=> DIV-5753: Implementing factory to select the right implementation of CSVExtractor

src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/config/DnCourtDetailsConfigValidationTest.java, src/test/resources/application.yml
Adds details for a new Court for Bulk Pronouncement in Birmingham.
https://tools.hmcts.net/jira/browse/DIV-5757
* Hardware:
* JDK:
=> Add Birmingham DN Court

dependency-check-suppressions.xml
Temporarily suppressed CVE-2019-16370 as it looks like there is no fix
Fixes #DIV-5762
=> DIV-5762 - temporarily suppressed CVE-2019-16370 as there is no fix

Jenkinsfile_CNP, src/integrationTest/java/uk/gov/hmcts/reform/divorce/RetryRule.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/IntegrationTest.java
This will disable the legacy Azure deployment and switch over the DNS
To the new K8S prod cluster
Fixes #DIV-5762
=> DIV-5762 - added disableLegacyDeployment() to switch deployment to AKS

charts/div-cos/values.aat.template.yaml, charts/div-cos/values.preview.template.yaml, infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/preview.tfvars, infrastructure/prod.tfvars, infrastructure/variables.tf, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/internal/DataExtractionInternalController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/AOSDataExtractor.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/CSVExtractorFactory.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/util/TaskUtils.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/internal/DataExtractionInternalControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/dataextraction/DataExtractionToFamilyManTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/AOSDataExtractorTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/CSVExtractorFactoryTest.java, src/test/resources/application.yml
- To facilitate the sending of AOS received and DN received events from CCD to FamilyMan via Robotics.
- Adhering to the CSV file format - headings and data fields as described in https://tools.hmcts.net/confluence/display/DIV/Divorce+-+Data+Feed+from+CCD+to+FamilyMan
https://tools.hmcts.net/jira/browse/DIV-5639
- unit tests for the AOS CSV extractor
- functional test
=> DIV-5639: AOS Data Extraction to CSV

charts/div-cos/values.aat.template.yaml, charts/div-cos/values.preview.template.yaml, infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/preview.tfvars, infrastructure/prod.tfvars, infrastructure/variables.tf, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/internal/DataExtractionInternalController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/AOSDataExtractor.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/CSVExtractor.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/CSVExtractorFactory.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DataExtractionFileCreator.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeAbsoluteDataExtractor.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeNisiDataExtractor.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/util/TaskUtils.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/CcdUtil.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/dataextraction/DataExtractionToFamilyManTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/AOSDataExtractorTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/CSVExtractorFactoryTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DataExtractionFileCreatorTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeAbsoluteDataExtractorTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeNisiDataExtractorTest.java, src/test/resources/application.yml
+ Create DN data extrator and accompanying tests
+ Added dn extractor emails in relevant files
* Hardware:
* JDK:
=> DIV 5641: Decree Nisi data extractor

infrastructure/main.tf
To stop deployment to the old legacy env in Azure
Fixes #DIV-5762
=> DIV-5762 - disable ASE deployment

src/integrationTest/java/uk/gov/hmcts/reform/divorce/dataextraction/FamilyManDataExtractionIT.java
=> Un-ignoring tests and adding instructions to run this locally.

charts/div-cos/values.aat.template.yaml
To debug CCD callbacks as they point at AAT staging
=> Added appinsights logs for div aat staging

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/ServiceMethodValidationTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CcdCallbackBulkPrintWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/BulkPrintTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/ServiceMethodValidationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CcdCallbackBulkPrintWorkflowTest.java
Only fail in issued state and service method is personal service
This is to allow bulk print to be triggered at a later stage in the journey
Fixes #DIV-4961
=> DIV-4961 - fixed solicitor bulk-print validation

src/main/resources/application.yml
Our requests to send e-mails seem to be hanging for all eternity.
=> Setting generous timeouts for Spring mail

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeAbsoluteDataExtractor.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/dataextraction/DataExtractionToFamilyManTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeAbsoluteDataExtractorTest.java
=> Remove DARequested State From DA Extractor

charts/div-cos/values.aat.template.yaml, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cos/CosApiClient.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/AosPackOfflineService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/AosPackOfflineServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/aospack/offline/RespondentAosAnswersProcessor.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/aospack/offline/AosPackOfflineAnswersWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/aospack/offline/AOSPackOfflineAnswersInputTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/aospack/offline/IssueAosPackOfflineTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/AosPackOfflineServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/aospack/offline/RespondentAosAnswersProcessorTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/aospack/offline/AosPackOfflineAnswersWorkflowTest.java
This has to be merged before https://github.com/hmcts/div-ccd-definitions/pull/290.
- [ x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
=> DIV-5718: Create a callback to decide the next state of a case when AOS offline is issued

build.gradle, job-scheduler/build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/divorce/dataextraction/FamilyManDataExtractionIT.java
Updates Jackson Databind based on [this CVE issue](https://nvd.nist.gov/vuln/detail/CVE-2019-16942)
=> [FAST] Fix-CVE-2019-16942 Apply Jackson update

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetDaGrantedDetailsTask.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DaAboutToBeGrantedDocumentsGeneration.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetDaGrantedDetailsTaskTest.java
correct the time zone of the da granted date
=> DIV-5847: Correct timezone for DA Granted

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetDNDecisionStateTask.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetDNDecisionStateTaskTest.java
=> DIV-5773 Add AwaitingAdminClarification state

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeNisiDataExtractor.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/dataextraction/DataExtractionToFamilyManTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeNisiDataExtractorTest.java
=> DIV-5641: Make CostClaimedGranted Optional

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/IntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/SubmitDnCaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/IdamUtils.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/FormatDivorceSessionToDnCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitDnCase.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeNisiDataExtractor.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DecreeNisiAboutToBeGrantedWorkflow.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SubmitDnCaseWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DecreeNisiAboutToBeGrantedTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SubmitDnCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/dataextraction/DataExtractionToFamilyManTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/FormatDivorceSessionToDnCaseDataUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitDnCaseUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeNisiDataExtractorTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DecreeNisiAboutToBeGrantedWorkflowTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SubmitDnCaseWorkflowUTest.java
=> Common Lib Conflict Resolution

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/aospack/offline/RespondentAosAnswersProcessor.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DataExtractionFileCreator.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/aospack/offline/RespondentAosAnswersProcessorTest.java
We were warned that we were using the online field for the offline journey.
Unit tests
=> DIV-5718: Using correct field for offline journey

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/aospack/offline/FormFieldValuesToCoreFieldsRelay.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/aospack/offline/AosPackOfflineAnswersWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/aospack/offline/AOSPackOfflineAnswersInputTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/aospack/offline/FormFieldValuesToCoreFieldsRelayTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/aospack/offline/AosPackOfflineAnswersWorkflowTest.java
Some form fields need to have their values relayed to other fields more significant fields.
=> DIV-5718 Some form fields need to have their values relayed to other fields

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/config/FeignRequestInterceptor.java, src/main/resources/application.yml
=> Add interceptor

build.gradle, job-scheduler/build.gradle
=> fix quartz vulnerabilty

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
=> Changed filenames for Rejection and Clarification Refusal Order docs

.gitignore, job-scheduler/.gitignore, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkScanController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/bulk/scan/validation/in/OcrDataField.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/bulk/scan/validation/in/OcrDataValidationRequest.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/bulk/scan/validation/out/OcrValidationResponse.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/bulk/scan/validation/out/ValidationStatus.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/MockedFunctionalTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/ValidationBulkScanITest.java, src/test/resources/jsonExamples/payloads/bulk/scan/validation/basicForm.json
Creating basic endpoint for scanned form validation.
Functional tests.
=> BSP-74: Creating basic endpoint for scanned form validation

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkScanController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/bulk/scan/validation/in/OcrDataField.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/bulk/scan/validation/in/OcrDataValidationRequest.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/bulk/scan/validation/out/OcrValidationResult.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/BulkScanForms.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/BulkScanFormValidator.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/BulkScanFormValidatorFactory.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidator.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkScanControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/ValidationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/BulkScanFormValidatorFactoryTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidatorTest.java, src/test/resources/jsonExamples/payloads/bulk/scan/basicForm.json, src/test/resources/jsonExamples/payloads/bulk/scan/validation/incompleteForm.json
Validating a few fields for the PoC.
=> BSP-73: Validating a subset of fields

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkScanController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/bulk/scan/validation/out/OcrValidationResponse.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/exception/bulk/scan/UnsupportedFormTypeException.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/BulkScanFormValidatorFactory.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkScanControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/ValidationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/BulkScanFormValidatorFactoryTest.java
Returning 404 http code for unsupported form type.
=> BSP-111: Returning 404 http code for unsupported form type

security.sh
Applied solution Suggested: https://tools.hmcts.net/confluence/display/RQA/Integrate+with+Glue+for+ignoring+false+postivies?focusedCommentId=1186104637&refresh=1570545877813#comment-1186104637
=> Nightly tests are failing for python2 and python3 compatibility

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkScanController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/bulk/scan/transformation/in/ExceptionRecord.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/bulk/scan/transformation/out/CaseCreationDetails.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/bulk/scan/update/in/BulkScanCaseUpdateRequest.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/bulk/scan/update/out/SuccessfulUpdateResponse.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/UpdateBulkScanITest.java
New endpoint for bulk scanning to update an existing case.
IT'S JUST A VERY FIRST ITERATION added to allow RBS to call anything on our side if they need to. There is no logic yet. There will be another stories to build it.
https://tools.hmcts.net/jira/browse/BSP-124
=> BSP-124: POST /update-case endpoint (POC)

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkScanController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/bulk/scan/validation/out/OcrValidationResult.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/helper/BulkScanHelper.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformations/D8FormToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/BulkScanFormValidator.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidator.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/BulkScanValidationService.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkScanControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/BulkScanValidationServiceTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidatorTest.java, src/test/resources/jsonExamples/payloads/bulk/scan/basicForm.json
https://tools.hmcts.net/jira/browse/BSP-88
Part 1 of 2 PRs for this ticket
=> BSP-88: D8 form section 1 validation and transformation

charts/div-cos/values.preview.template.yaml
Correctly indented Postgresql in Preview charts to fix our Jenkins pipeline for COS
=> Indent postgresql to fix pipeline

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformations/D8FormToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformations/ExceptionRecordToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/BulkScanFormValidator.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidator.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/TransformationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/ValidationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformation/D8FormToCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidatorTest.java, src/test/resources/jsonExamples/payloads/bulk/scan/fullD8Form.json, src/test/resources/jsonExamples/payloads/bulk/scan/partialD8Form.json
https://tools.hmcts.net/jira/browse/BSP-87
https://tools.hmcts.net/jira/browse/BSP-90
Adding validation for the following fields:
D8HelpWithFeesReferenceNumber
D8PaymentMethod
D8RespondentFirstName
D8RespondentLastName
=> BSP-87 and BSP-90 Validation & Transformation

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/exception/FormFieldValidationException.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/helper/BulkScanHelper.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformations/D8FormToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformations/ExceptionRecordToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/BulkScanFormValidator.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidator.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/TransformationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformation/D8FormToCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidatorTest.java, src/test/resources/jsonExamples/payloads/bulk/scan/fullD8Form.json
Validating and converting separation date
=> BSP-104: Converting and validating separation date

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/helper/BulkScanHelper.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformations/D8FormToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidator.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/ValidationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/helper/BulkScanHelperTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidatorTest.java
29 of February in year that are not leap years should fail validation.
Unit tests.
=> BSP-104: Fail wrong leap year dates.

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/BulkScanValidationPatterns.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformations/D8FormToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidator.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/TransformationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/ValidationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidatorTest.java, src/test/resources/jsonExamples/payloads/bulk/scan/fullD8Form.json, src/test/resources/jsonExamples/payloads/bulk/scan/partialD8Form.json, src/test/resources/jsonExamples/payloads/bulk/scan/validation/warningsD8Form.json
https://tools.hmcts.net/jira/browse/BSP-89 and
https://tools.hmcts.net/jira/browse/BSP-100
Validation and Transformation of Section 2 Parts 1 and 2 of the D8 Divorce form
Unit and integration tests
=> BSP-89 and BSP-100: Section 2 Parts 1 and 2 Validation and Transformation

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/helper/PostcodeValidator.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformations/D8FormToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidator.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/TransformationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/helper/PostcodeValidatorTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformation/D8FormToCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidatorTest.java
=> BSP-100 and BSP-90: Postcode transformation and negative validation tests; Respondent phone number validation

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformations/D8FormToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidator.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/TransformationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/ValidationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformation/D8FormToCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidatorTest.java, src/test/resources/jsonExamples/payloads/bulk/scan/fullD8Form.json, src/test/resources/jsonExamples/payloads/bulk/scan/validation/warningsD8Form.json
https://tools.hmcts.net/jira/browse/BSP-101
Unit and integration tests
=> BSP-101: D8 Section 2 - Petitioner Solicitor fields validation and transformation

infrastructure/demo.tfvars
=> Adding in variables that are also in aat

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformations/D8FormToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidator.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/TransformationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformation/D8FormToCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidatorTest.java, src/test/resources/jsonExamples/payloads/bulk/scan/fullD8Form.json
Adding validation and transformation logic for petitioner address fields.
Fixes [BSP-122](https://tools.hmcts.net/jira/browse/BSP-122)
Unit tests added.
=> D8PetitionerHomeAddressStreet field validation and transformation added

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformations/D8FormToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidator.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/TransformationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformation/D8FormToCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidatorTest.java, src/test/resources/jsonExamples/payloads/bulk/scan/fullD8Form.json
Added validation and transformation logic for the co-respondent details (i.e. name and address).
Fixes [BSP-106](https://tools.hmcts.net/jira/browse/BSP-106)
Unit tests and functional test.
=> Bsp 106 adultery section 3rd party

src/main/resources/application.yml, src/test/resources/application.yml
=> Adding configuration for bsp services via env vars

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidator.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidatorTest.java
Validation logic added:
- Address fields should be empty if useHomeAddress = Yes
- Address fields should not be empty if useHomeAddress = No
Fixes https://tools.hmcts.net/jira/browse/BSP-122
Added Unit tests
=> presence of address fields depends on condition: useHomeAddress

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformations/D8FormToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidator.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/TransformationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/ValidationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformation/D8FormToCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidatorTest.java, src/test/resources/jsonExamples/payloads/bulk/scan/fullD8Form.json, src/test/resources/jsonExamples/payloads/bulk/scan/validation/warningsD8Form.json
Validation and transformation added for 'apply for financial order' section.
Fixes https://tools.hmcts.net/jira/browse/BSP-109
Unit tests added, and functional tests updated
=> Bsp 109 apply for financial order

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformations/D8FormToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidator.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/TransformationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/ValidationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidatorTest.java, src/test/resources/jsonExamples/payloads/bulk/scan/fullD8Form.json, src/test/resources/jsonExamples/payloads/bulk/scan/validation/warningsD8Form.json
Validation and transformation for the reason for divorce field.
Fixes https://tools.hmcts.net/jira/browse/BSP-93
Unit tests added, and functional tests updated.
=> Bsp 93 reason for divorce

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformations/D8FormToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidator.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/TransformationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/ValidationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidatorTest.java, src/test/resources/jsonExamples/payloads/bulk/scan/fullD8Form.json, src/test/resources/jsonExamples/payloads/bulk/scan/validation/warningsD8Form.json
Validation and transformation logic for section 9: existing court cases.
Fixes https://tools.hmcts.net/jira/browse/BSP-108
Unit tests added, and functional tests updated.
=> existing court cases, validation and transformation

build.gradle
- Deleted duplicated lines
- Grouped properly and alphabetised 
- Bumped some minor version numbers
=> Made Gradle file sparkling clean

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformation/AosPackOfflineFormToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformation/BulkScanFormTransformer.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformation/BulkScanFormTransformerFactory.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformation/D8FormToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/D8FormValidator.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/BulkScanService.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/TransformationBulkScanITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformation/AosPackOfflineFormToCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformation/BulkScanFormTransformerFactoryTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformation/D8FormToCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/BulkScanServiceTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/D8FormValidatorTest.java, src/test/resources/jsonExamples/payloads/bulk/scan/d8/fullD8Form.json
Developed BSP-110: Section 11 - Statement of truth - of the D8 form.
Unit and functional tests
=> BSP-110: Section 11 - Statement of truth

build.gradle
=> Updating sonar path

build.gradle, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/event/bulkscan/BulkScanEvents.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/TransformationBulkScanITest.java
Using correct name for bulk scanning case creation event.
Functional tests.
=> BSP-164: Changing the name the case creation event (Bulk scanning)

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/D8FormValidator.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/D8FormValidatorTest.java
D8SolicitorsFirmStatementOfTruth should be optional.
Unit tests.
=> D8SolicitorsFirmStatementOfTruth should be optional

dependency-check-suppressions.xml
After multiple attempts to find out the cause of the health check test failures in #691, the Spring version update is suppressed for the time being pending further investigation as it renders the builds unstable.
* Hardware:
* JDK:
=> FIX-Spring suppression CVE-2020-5398

charts/div-cos/values.yaml, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeAbsoluteDataExtractor.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/dataextraction/DataExtractionToFamilyManTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeAbsoluteDataExtractorTest.java
https://tools.hmcts.net/jira/browse/RPET-38
=> RPET38 remove da application date from da extractor

charts/div-cos/Chart.yaml, charts/div-cos/values.yaml, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeAbsoluteDataExtractor.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/dataextraction/DataExtractionToFamilyManTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeAbsoluteDataExtractorTest.java
Reverts hmcts/div-case-orchestration-service#690
=> Revert "RPET38 remove da application date from da extractor"

charts/div-cos/Chart.yaml, charts/div-cos/values.yaml, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeAbsoluteDataExtractor.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/dataextraction/DataExtractionToFamilyManTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeAbsoluteDataExtractorTest.java
Reverts hmcts/div-case-orchestration-service#698
After we run the scripts, we want to go back to the fixed version on the DA file.
=> Revert "Revert "RPET38 remove da application date from da extractor""

build.gradle, checkstyle.xml, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkScanController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/documentgeneration/GenerateDocumentRequest.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformation/BulkScanFormTransformerFactory.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/BulkScanFormValidatorFactory.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/CSVExtractorFactory.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DataExtractionEmailClient.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/ExtractedDataPublisher.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/dataextraction/DataExtractionToFamilyManTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/PopulateDocLinkTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DataExtractionEmailClientTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/ExtractedDataPublisherTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/AosSubmissionWorkflowTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DataExtractionWorkflowTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/NotifyRespondentOfDARequestedWorkflowTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SeparationFieldsWorkflowTest.java
=> fix owasp vulnerability

charts/div-cos/Chart.yaml, charts/div-cos/values.demo.template.yaml
Adding a demo COS chart config file.
=> Adding a demo COS chart config file

infrastructure/demo.tfvars
Bringing demo-specific infra configuration to master.
Manual tests in demo.
=> Configuring demo infra

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CalculateDecreeAbsoluteDates.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/decreeabsolute/ProcessApplicantDAEligibilityTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CalculateDecreeAbsoluteDatesTest.java
Three months should be added after the 6 weeks and 1 day period.
Unit tests
=> Fixed DA date calculation

.editorconfig, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkScanController.java
Adding logs to BSP transformation endpoint. This will give us more information about the integration with BSP.
=> Adding logs to BSP transformation endpoint.

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkScanController.java
These will not be rolled out to prod when we release BSP divorce. They're only useful for us to know what BSP sends us in the tests and what we send to them.
=> Adding more logs (temporarily)

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkScanController.java
These logs expose too much about user data.
=> Removing unnecessary logs

src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/ServiceContextConfiguration.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/config/TemplateConfig.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/TemplateConfigService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/TemplateConfigServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendDaRequestedNotifyRespondentEmailTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendRespondentCertificateOfEntitlementNotificationEmail.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendRespondentSubmissionNotificationForDefendedDivorceEmail.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendRespondentSubmissionNotificationForUndefendedDivorceEmail.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/notification/NotifyForRefusalOrderTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/CaseDataUtils.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/AosSubmissionWorkflow.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/TestConstants.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/config/TemplateConfigTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RespondentAOSSubmissionNotificationEmailITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/TemplateConfigServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendDaRequestedNotifyRespondentEmailTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendRespondentCertificateOfEntitlementNotificationEmailTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendRespondentSubmissionNotificationEmailTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/notification/NotifyForRefusalOrderTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/util/CaseDataUtilsTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/AosSubmissionWorkflowTest.java, src/test/resources/application.yml
Code Re-fector and introduce few thing application.yml
- [x ] New feature (non-breaking change which adds functionality)
* Hardware:
* JDK:
=> WLA-329: code-refector-welsh-date-relation

charts/div-cos/Chart.yaml, charts/div-cos/requirements.yaml, dependency-check-suppressions.xml
Add Netty vulnerability suppression for:
**Ignore hyperlinks below**
- CVE-2019-20444
- CVE-2019-20445
- CVE-2020-11612
- CVE-2020-7238
- CVE-2020-7009
* Hardware:
* JDK:
=> Add Netty vulnerability suppression

src/test/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/pay/PaymentItemTest.java
Add unit tests to cover positive and negative scenarios to calculate the amount.
https://tools.hmcts.net/jira/browse/DIV-4968
* Hardware:
* JDK:
=> Add unit tests for setCalculatedAmount

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendDaGrantedNotificationEmailTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/notification/SendDaGrantedNotificationEmailWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendDaGrantedNotificationEmailTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/notification/SendDaGrantedNotificationEmailTaskWorkflowTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/notification/SendDaGrantedNotificationEmailWorkflowTest.java
Just renaming SendDaGrantedNotificationEmail to SendDaGrantedNotificationEmailTask as a clean up before we actually start working on DIV-6313.
No logic updated.
##Jira 
https://tools.hmcts.net/jira/browse/DIV-6313
=> DIV-6313: SendDaGrantedNotificationEmail -> SendDaGrantedNotificationEmailTask

build.gradle, charts/div-cos/Chart.yaml, dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/D8FormValidator.java
Upgrading packages to the latest stable
=> Upgrading packages

src/main/resources/example-application-aat.yml
updated example-application-aat.yml to setup local env to run int tests
=> DIV-6313: updated example-application-aat.yml

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/BulkPrinterTask.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/BulkPrinterTaskTest.java
reported in JIRA:
https://tools.hmcts.net/jira/browse/RPET-234
=> revert update of code that was displaying an error in CCD UI

src/main/resources/example-application-aat.yml
Updated example-application.yml config file
=> added feature flag to example-application.yml config file

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/BulkPrintCallbackTest.java, src/integrationTest/resources/fixtures/issue-petition/ccd-callback-aos-invitation-service-centre-with-coRespondent.json, src/integrationTest/resources/fixtures/issue-petition/ccd-callback-aos-invitation.json, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/FetchPrintDocsFromDmStore.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/BulkPrinterTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/CaseDataUtils.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CcdCallbackBulkPrintWorkflow.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/IssueEventWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/BulkPrinterTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/util/CaseDataUtilsTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CcdCallbackBulkPrintWorkflowTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/IssueEventWorkflowTest.java
Also, test scenario that broke production has been added.
=> RPET-234: Returning check about bulk print documents matching the expected types

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetDNDecisionStateTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitRespondentAosCase.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/WelshSetPreviousStateTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/WelshNextEventUtil.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DecreeNisiAboutToBeGrantedWorkflow.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetDNDecisionStateTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitRespondentAosCaseUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/WelshSetPreviousStateTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/util/WelshNextEventUtilTest.java, src/test/resources/application.yml
WLA-464 Legal Advisor Refuses a Decree Nisi and enters free format text as an explanation (Requests Clarification Details or Gives rejection details) :
https://tools.hmcts.net/jira/browse/WLA-464
- [ x] New feature (non-breaking change which adds functionality)
Integration and unit tested
* Hardware:
* JDK:
=> Wla 464 v1

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/CaseDataUtils.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DecreeNisiAboutToBeGrantedWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetDNDecisionStateTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/util/CaseDataUtilsTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DecreeNisiAboutToBeGrantedWorkflowTest.java
Decree Nisi stop check updates
https://tools.hmcts.net/jira/browse/WLA-514
- [ x] New feature (non-breaking change which adds functionality)
Unit tested
* Hardware:
* JDK:
=> WLA-514: Decree Nisi stop check updates

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendDaGrantedNotificationEmailTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/PartyRepresentationChecker.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/AosSubmissionWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendDaGrantedNotificationEmailTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/util/PartyRepresentationCheckerTest.java
https://tools.hmcts.net/jira/browse/DIV-6348
Just reuse new utils for isRepresented
=> DIV-6348: reuse new utils

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/task/TaskContextHelper.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/BasePayloadSpecificDocumentGenerationTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/DaGrantedLetterGenerationTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/aospack/offline/AosPackOfflineAnswersWorkflow.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/notification/SendDaGrantedNotificationWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/task/TaskContextHelperTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/aospack/offline/CoRespondentAosAnswersProcessorTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/DaGrantedLetterGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/notification/SendDaGrantedNotificationWorkflowTest.java
Code review changes for https://tools.hmcts.net/jira/browse/DIV-6313
=> DIV-6313: Code review

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/BulkPrinterTask.java
=> log.info in BulkPrinterTask to get more details about docs sent to bulk printing

src/integrationTest/resources/fixtures/da-granted/da-granted-digital-no.json, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/BulkPrinterTask.java
Enhancing BulkPrint logs to assist in verifying what documents actually gets sent to the BulkPrint service.
https://tools.hmcts.net/jira/browse/DIV-6313
=> DIV-6313: Updating BulkPrint to except printing bytes to logs

build.gradle, job-scheduler/build.gradle, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/documentgeneration/GeneratedDocumentInfo.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/BulkPrinterTask.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/BulkPrinterTaskTest.java
We need better logs for these documents.
=> DIV-6339: Fixing bulk print document log messages

dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetDNDecisionStateTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/WelshSetPreviousStateTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/CaseDataUtils.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetDNDecisionStateTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/WelshSetPreviousStateTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/util/CaseDataUtilsTest.java, src/test/resources/application.yml
LA refusal clarification missing Auto stop functionality
https://tools.hmcts.net/jira/browse/WLA-561
Unit and integration tested
* Hardware:
* JDK:
=> WLA-561: LA refusal clarification (option 2) Auto stop functionality

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/CaseDataUtils.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DecreeNisiAboutToBeGrantedWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/util/CaseDataUtilsTest.java
Added TypeCostsDecision field in check
* Hardware:
* JDK:
=> WLA-561 DIVORCE: added claim cost order auto stop check

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/BulkPrintCallbackTest.java
This test seems to be broken quite often and I'd like to see more details in logs.
=> More details displayed in logs when test is broken

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SendDnPronouncedNotificationWorkflow.java
Add logs to Co-Respondent costs order flow
=> Add logs to Co Respondent cost order flow

src/main/resources/example-application-aat.yml
new values in application.yml were not added to example-application-aat.yml
=> update file example-application-aat.yml

src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/ServiceContextConfiguration.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cms/CmsClientSupport.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/internal/DecreeAbsoluteCaseInternalController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/bulk/print/BasicCoverLetter.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/bulk/print/CoECoverLetter.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/bulk/print/CoRespondentCostOrderCoverLetter.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/bulk/print/CoRespondentCostOrderNotificationCoverLetter.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/bulk/print/DocmosisTemplateVars.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/DefaultWorkflow.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/TaskCommons.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/DaGrantedLetterGenerationTask.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/TestConstants.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/AddresseeDataExtractorTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/FullNamesDataExtractorTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CostOrderCoRespondentCoverLetterGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CostOrderCoRespondentSolicitorCoverLetterGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/BasePayloadSpecificDocumentGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/BulkPrintTestData.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/CoECoRespondentCoverLetterGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/DaGrantedLetterGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SendDnPronouncedNotificationWorkflowTest.java
Migrating the existing scenarios that weren't covered as part of https://github.com/hmcts/div-case-orchestration-service/pull/845
* Hardware:
* JDK:
=> DIV-6348 - migrating existing doc generation tasks to new test model

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/DocumentType.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DocumentGenerationWorkflow.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/DocumentTypeTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/DocumentTemplateServiceTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DocumentGenerationWorkflowTest.java, src/test/resources/application.yml
Certificate Of entitlement not translated to Welsh
https://tools.hmcts.net/jira/browse/WLA-502
Unit and integration tested
* Hardware:
* JDK:
=> WLA-502: Certificate Of entitlement not translated to Welsh

build.gradle
Fixing bootRunAat task on new gradle version
* Hardware:
* JDK:
=> Fixing bootRunAat task on new gradle version

build.gradle, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/BasePayloadSpecificDocumentGenerationTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SendDnPronouncedNotificationWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/BasePayloadSpecificDocumentGenerationTaskTest.java
Changed the way of generating a list of documents to print. Not always there will be 2 elements.
=> DIV-5823: more logs

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CaseLinkedForHearingWorkflow.java
Use common method for checking party is digital.
This is to ensure, this would return yes by default, if the value of this field was missing.
Fixes https://tools.hmcts.net/jira/browse/DIV-5622
=> DIV-5622 use common method for checking party is digital

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/CoERespondentCoverLetterGenerationTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/DnGrantedRespondentCoverLetterGenerationTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/DnGrantedRespondentSolicitorCoverLetterGenerationTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CaseLinkedForHearingWorkflow.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SendDnPronouncedNotificationWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DnPronouncedNotificationTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/MockedFunctionalTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/callback/CaseListedForHearingCallbackTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/AddresseeDataExtractorTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/CoERespondentCoverLetterGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/CoERespondentLetterGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/DaGrantedCitizenLetterGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/DnGrantedRespondentCoverLetterGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/DnGrantedRespondentSolicitorCoverLetterGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CaseLinkedForHearingWorkflowTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SendDnPronouncedNotificationWorkflowTest.java
Sending Your DN is granted (and cost order) letter to respondent/ solicitor.
It uses MultiBulkPrinter task as there are also some documents for co-resp.
https://tools.hmcts.net/jira/browse/DIV-6317
=> DIV-6317: bulk printing

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/MultiBulkPrinterTask.java
=> DIV-6317: better logs

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/SolicitorDataExtractor.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/SolicitorDataExtractorTest.java
Solicitor reference made optional.
Fixes Solicitor reference made optional
=> DIV-6407: Solicitor reference made optional

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/ProcessAosPackOfflineAnswers.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cos/CosApiClient.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/AosPackOfflineService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/AosPackOfflineServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/aospack/offline/AosPackOfflineAnswersWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/aospack/offline/AOSPackOfflineAnswersInputTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/AosPackOfflineServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/testutil/Verificators.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/aospack/offline/AosPackOfflineAnswersWorkflowTest.java
Producing respondent answers documents for offline AOS.
Integration, functional and unit tests.
=> DIV-6361: Producing respondent answers documents for offline AOS

src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/BulkPrintTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DnPronouncedNotificationTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/IdamTestSupport.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/MockedFunctionalTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/ProcessPbaPaymentITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RespondentSolicitorNominatedITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/aospack/offline/IssueAosPackOfflineTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/callback/CaseListedForHearingCallbackTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/callback/DaGrantedCallbackTest.java
Let's get there one bit at a time.
Functional tests.
=> DIV-6412: Made functional tests a little lighter

build.gradle, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/FetchPrintDocsFromDmStore.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/RespondentSolicitorNominatedWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/TestConstants.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/PetitionIssuedITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/ProcessPbaPaymentITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RespondentSolicitorNominatedITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RetrieveDraftITest.java
There's still one test that uses the "DirtiesContext annotation". I'll to tackle this until the end of the sprint, if we have capacity.
=> DIV-6412: Made more tests lighter and more reliable

build.gradle
Upgrading tomcat to deal with dependency vulnerability issue.
=> Upgrading tomcat to deal with dependency vulnerability issue

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseMaintenanceClient.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CreateAmendPetitionDraftForRefusalFromCaseIdTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SolicitorSubmitCaseToCCDTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CreateNewAmendedCaseAndSubmitToCCDWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SolicitorAmendPetitionForRefusalITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CreateAmendPetitionForRefusalFromCaseIdTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SolicitorSubmitCaseToCCDTaskTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CreateNewAmendedCaseAndSubmitToCCDWorkflowTest.java
New endpoint to allow solicitors to amend petition for dn rejection.
Fixes https://tools.hmcts.net/jira/browse/DIV-6198
=> DIV-6198: Solicitor amend petition for refusal

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/notification/SendPetitionerAmendEmailTask.java
More logs
https://tools.hmcts.net/jira/browse/DIV-6191
=> DIV-6191: more logs

charts/div-cos/values.aat.template.yaml
As it turns out, AAT (staging) doesn't use the same flux config as AAT. It uses the values.yaml file.
I'm not taking chances right now. I'll only edit the AAT version of it.
=> Fixing environment variables

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SendPetitionerEmailNotificationWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/AosOverdueNotificationTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SendPetitionerEmailNotificationWorkflowTest.java
We must feature toggle this on prod:
https://tools.hmcts.net/jira/browse/DIV-6388
=> DIV-6388: feature toggle

charts/div-cos/values.preview.template.yaml, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/LinkRespondentTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/SubmitDnCaseTest.java
=> disabling failing functional test

src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/LinkRespondentTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/SubmitDnCaseTest.java
=> WLA-494: Enable failing tests

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/ReceivedServiceAddedDateTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/AmendPetitionForRefusalWorkflow.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/AmendPetitionWorkflow.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/ReceivedServiceAddedDateWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/ReceivedServiceAddedDateTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/ReceivedServiceAddedDateTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/testutil/Verificators.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/ReceivedServiceAddedDateWorkflowTest.java
Added an endpoint:
```
POST /received-service-added-date
```
https://tools.hmcts.net/jira/browse/DIV-6431
=> DIV-6431: POST /received-service-added-date

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/ReceivedServiceAddedDateWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/ReceivedServiceAddedDateWorkflowTest.java
More logs to see what is going on:
https://tools.hmcts.net/jira/browse/DIV-6431
=> DIV-6431: added logs and more unit tests

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerSubmissionNotificationEmailTask.java
more logs to see what is going on
=> DIV-6196: more logs

src/main/resources/example-application-aat.yml
The units have to be specified.
Integration tests.
=> Fixing local integration tests

src/integrationTest/resources/fixtures/issue-petition/solicitor-petition.json
Adding new mandatory field to example case.
Integration tests
=> Fixing broken master pipeline

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerSubmissionNotificationEmailTask.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/ProcessPbaPaymentITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerSubmissionNotificationEmailTaskTest.java
https://tools.hmcts.net/jira/browse/DIV-6196
=> DIV-6196: 'solicitor name' var for email APPLIC_SUBMISSION_AMEND_SOLICITOR

src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/ServiceContextConfiguration.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/AosOverdueTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/util/ElasticSearchTestHelper.java, src/integrationTest/resources/fixtures/issue-petition/submit-complete-case.json, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/event/listener/AosOverdueRequestListener.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/job/AosOverdueJob.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/AosService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/AosServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/aos/MarkAosCasesAsOverdueTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/aos/AosOverdueEligibilityWorkflow.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/aos/AosOverdueWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/event/listener/AosOverdueRequestListenerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/MockedFunctionalTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/aos/AosOverdueTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/job/AosOverdueJobTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/AosServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/aos/AosOverdueEligibilityWorkflowTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/aos/AosOverdueWorkflowTest.java
This will call the event that will move the eligible case to AOSOverdue.
=> DIV-6438: Moving eligible cases to AOS Overdue

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/ccd/CcdCallbackResponse.java
Our ticket:
https://tools.hmcts.net/jira/browse/DIV-6236
Reason why we need to do it:
https://tools.hmcts.net/jira/browse/RDM-6970
=> DIV-6236: CcdCallbackResponse.state added

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerSubmissionNotificationEmailTask.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerSubmissionNotificationEmailTaskTest.java
Edge case: new case submitted, no pet email -> don't send any emails.
https://tools.hmcts.net/jira/browse/DIV-6196
=> DIV-6196: when new case and no pet email - don't send email at all

build.gradle, src/main/resources/application.yml, src/main/resources/example-application-aat.yml
=> Removing duplicate court information.

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/advice/GlobalExceptionHandler.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/task/InvalidDataForTaskException.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/task/TaskException.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationServiceException.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/helper/ExtractorHelper.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/PetitionSubmissionNotificationEmailITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationServiceExceptionTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerSubmissionNotificationEmailTaskTest.java
This can still be improved and this code can be reused by other callback endpoints (maybe even handled globally), but we don't have time for this right now.
The usual
=> Linking callback error to case id

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/document/ApplicationServiceTypes.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/document/ServiceDecisionOrder.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/BasePayloadSpecificDocumentGenerationTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/CoECoRespondentCoverLetterGenerationTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/DaGrantedSolicitorLetterGenerationTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/DeemedServiceOrderGenerationTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/ServiceDecisionOrderGenerationTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/servicejourney/MakeServiceDecisionDateWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/MakeServiceDecisionTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/BasePayloadSpecificDocumentGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/DeemedServiceOrderGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/ServiceDecisionOrderGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/MakeServiceDecisionDateWorkflowTest.java
Story:
https://tools.hmcts.net/jira/browse/DIV-6238
Other PRs:
template: https://github.com/hmcts/rdo-docmosis/pull/373
GDS: https://github.com/hmcts/div-document-generator-client/pull/355
CCD: https://github.com/hmcts/div-ccd-definitions/pull/440
=> DIV-6238: logic for Deemed service order

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/CcdStates.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/ServiceJourneyServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/MakeServiceDecisionTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/ServiceJourneyServiceImplTest.java
Spotted in refinement of next story.
=> DIV-5411: use 'AwaitingDecreeNisi' state instead of 'AwaitingDNApplication'

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/ApplicationWithoutNoticeTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cos/CosApiClient.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SetupServicePaymentEventTest.java
Integration tests for `/set-up-confirm-service-payment` callback endpoint.
https://tools.hmcts.net/jira/browse/DIV-6213
https://tools.hmcts.net/jira/browse/DIV-6493
Base PR:
https://github.com/hmcts/div-case-orchestration-service/pull/950
=> DIV-6213: integration tests for '/set-up-confirm-service-payment' endpoint

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SetupConfirmServicePaymentWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SetupServicePaymentTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SetupConfirmServicePaymentWorkflowTest.java
=> DIV-6213: remove 'Event' from names of classes

Jenkinsfile_nightly
I've replace HTTPs with HTTP to fix the issue which we are getting with security check on nightly.
=> Security Fix

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/DocumentContentFetcherService.java
Hopefully this will please the Sonar gods.
=> Fixing issue pointed out by Sonar

hs_err_pid36539.log, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/courtallocation/GenericCourtWeightedDistributorTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/AddCourtsToPayloadTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/FormatDivorceSessionToCaseDataTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/MultipleDocumentGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitCoRespondentAosCaseUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/aos/AosOverdueCoverLetterGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DataExtractionEmailClientTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/util/TaskUtilsTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/aos/AosNotReceivedWorkflowTest.java
ExpectedException.none is now deprecated. I've addressed some of the warnings caused by it.
=> Handled a few warnings

build.gradle
=> RPET436: bump ccdStoreClient to 4.7.3

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/config/JudgeTypesConfig.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/exception/JudgeTypeNotFoundException.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/JudgeTypesLookupService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/generalorders/GeneralOrderDraftGenerationTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/generalorders/GeneralOrderGenerationTask.java, src/main/resources/application.yml, src/main/resources/example-application-aat.yml, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/generalorders/GeneralOrderTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/JudgeTypesLookupServiceTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/generalorders/AbstractGeneralOrderGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/generalorders/GeneralOrderGenerationTaskTest.java, src/test/resources/application.yml
mapping judge type codes provided from ccd to human readable strings.
=> DIV-6142: Judge Type Lookup

src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/AosOverdueTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/util/ElasticSearchTestHelper.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DataExtractionEmailClientTest.java
Hopefully this will make this ES test less flaky.
=> Increase AOSOverdue test timeout

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/GeneralEmailWorkflow.java
https://tools.hmcts.net/jira/browse/DIV-6502
Moved away from dynamic logs to specific hard coded examples
=> DIV-6502-Improve logging

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/GetPetitionIssueFeesTest.java, src/main/resources/application.yml, src/main/resources/example-application-aat.yml, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/util/CaseOrchestrationValuesTest.java, src/test/resources/application.yml
This makes the AOS Overdue grace period into zero days. That's better than changing the environment variable as it makes the business rule more evident.
**DO NOT MERGE UNTIL WE HAVE CONFIRMATION FROM MANAGEMENT.** 
=> DIV-6557: Setting the default grace period to be zero days.

charts/div-cos/Chart.yaml, charts/div-cos/values.yaml, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/PBAValidationClient.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/pay/validation/ContactInformationResponse.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/pay/validation/DxAddressResponse.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/pay/validation/OrganisationEntityResponse.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/pay/validation/PBAOrganisationResponse.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/pay/validation/SuperUserResponse.java, src/main/resources/application.yml, src/main/resources/example-application-aat.yml, src/test/resources/application.yml
Adding PRD client to COS to allow COS to call PRD service.
Fixes https://tools.hmcts.net/jira/browse/DIV-6208
=> DIV-6208: Adding PRD client

build.gradle
Spring boot version raised up to fix security vulnerabilities
=> Spring boot version raised up to fix security vulnerabilities

src/integrationTest/java/uk/gov/hmcts/reform/divorce/draft/DraftServiceEndToEndTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/RetrieveCaseTest.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CaseDataDraftToDivorceFormatter.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RetrieveDraft.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/UserDivorcePartyLookup.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RetrieveDraftITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CaseDataDraftToDivorceFormatterTest.java
Filtering general orders applied to draft endpoint.
Usual tests
=> DIV-6496: Implementing filtering of general orders to the draft endpoint

src/integrationTest/resources/fixtures/issue-petition/solicitor-submit-personal-service.json, src/integrationTest/resources/fixtures/solicitor/solicitor-request-data-dn-rejection.json, src/integrationTest/resources/fixtures/solicitor/solicitor-request-data.json
=> fix master PBA number

build.gradle
Removing 'T', causing issues in the frontends.
Fixes https://tools.hmcts.net/jira/browse/DIV-6596
=> DIV-6596: Refactoring document names

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/SolicitorPersonalServiceCallbackTest.java, src/integrationTest/resources/fixtures/issue-petition/solicitor-submit-personal-service.json
"PbaNumbers" is a mandatory field when PBA feature toggle is on.
=> Unblocking master pipeline

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/CcdFields.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/GeneralReferralService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/GeneralReferralServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/generalreferral/GeneralApplicationAddedDateTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/generalreferral/GeneralReferralWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/generalreferral/GeneralReferralTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/GeneralReferralServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/generalreferral/GeneralApplicationAddedDateTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/generalreferral/GeneralReferralWorkflowTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/generalreferral/SetupConfirmServicePaymentWorkflowTest.java
Populate `GeneralApplicationAddedDate` field on `GeneralReferral`.
Story:
https://tools.hmcts.net/jira/browse/DIV-6168
=> DIV-6168: populate 'GeneralApplicationAddedDate' with 'today' on 'GeneralReferral'

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/CcdFields.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/task/generics/FeeLookupWithoutNoticeTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/generalreferral/GetGeneralReferralApplicationFeeTask.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/task/generics/FeeLookupWithoutNoticeTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/generalreferral/SetupGeneralReferralPaymentTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/generalreferral/GetGeneralReferralApplicationFeeTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/testutil/FeesAndPaymentHelper.java
Story:
https://tools.hmcts.net/jira/browse/DIV-6166
=> DIV-6166: populate FeeAmountWithoutNotice field

Jenkinsfile_nightly, src/integrationTest/resources/fixtures/da-granted/da-granted-offline-represented-respondent.json, src/integrationTest/resources/fixtures/da-granted/da-granted-offline.json, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DnPronouncedNotificationTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/callback/DaGrantedCallbackTest.java
This change adds the Functional API Tests to the nightly test pipeline. This will provide data on stability of tests running inside and outside peak times. This data will be used to better understand API test flakiness and eventually improve build pipeline stability (e.g. flakey tests might be moved to more stable nightly run times where safe to do so)
Fixes # (TA-141)
This has been run via the nightly pipeline and can be seen to re-run failed tests which have passed the 2nd time
=> feature(TA-12): Run full API tests in nightly pipeline

build.gradle, dependency-check-suppressions.xml
upgrading tomcat to latest version and suppressing dependency failures for a month as the issue still persists
https://github.com/jeremylong/DependencyCheck/issues/2926
https://hmcts-reform.slack.com/archives/C8SR5CAMU/p1603811478231300
=> upgrading tomcat to latest version and suppressing dependency failures for a month

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/ProcessPbaPaymentTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/SolicitorCreateAndUpdateTest.java, src/integrationTest/resources/fixtures/solicitor/payment/active-account-request.json, src/integrationTest/resources/fixtures/solicitor/payment/help-with-fee-request.json, src/integrationTest/resources/fixtures/solicitor/payment/inactive-account-request.json, src/integrationTest/resources/fixtures/solicitor/payment/insufficient-funds-request.json, src/integrationTest/resources/fixtures/solicitor/payment/missing-data-request.json, src/integrationTest/resources/fixtures/solicitor/payment/nonexisting-account-request.json
PBA has a mechanism that fails request with the same case id in less than 2 minutes.
=> DIV-6612: Generating random case number for each test.

charts/div-cos/Chart.yaml, charts/div-cos/values.yaml
This logic was brought from CFS into (effectively) COS. However, the configuration for this environment variable was missing in COS.
- [ X ] Bug fix (non-breaking change which fixes an issue)
Manually tested on PR environment.
=> Missing environment variable that only exists in CFS, but not in COS

build.gradle, dependency-check-suppressions.xml
COS was failing due to a JUnit dependency vulnerability.
As this is not soemthing that is used in prod, @johnoneill46 and I agree that it is suitable to supress.
=> Fix broken pipeline

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/CcdFields.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/alternativeservice/MarkJourneyAsServedByProcessServerTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/alternativeservice/ConfirmAlternativeServiceWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/alternativeservice/ConfirmProcessServerServiceTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/alternativeservice/MarkJourneyAsServedByProcessServerTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/alternativeservice/ConfirmAlternativeServiceWorkflowTest.java
Mark case as served by process server service
Fixes https://tools.hmcts.net/jira/browse/DIV-6177
Added unit tests and modified functional test
=> DIV-6177: Mark journey as served by process server

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/courts/DnCourt.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/courts/DnCourtTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CourtLookupServiceTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetFormattedDnCourtDetailsTest.java
=> Using apache commons empty space.

build.gradle
https://tools.hmcts.net/jira/browse/DIV-6180
Adding served by process service data to session data in common lib project
=> DIV-6180-Bumping-up-version-to-v1.2.1-for process-server-service

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/aos/MarkCasesAsAosOverdueTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/elasticsearch/CMSElasticSearchSupport.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/aos/MarkCasesAsAosOverdueTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/util/elasticsearch/CMSElasticSearchSupportTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/util/elasticsearch/CMSElasticSearchUtils.java
Trying to make tests a bit clearer and easier.
=> DIV-6178: Trying to make tests a little easier and clearer

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/CcdStates.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateRespondentDetails.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateRespondentDetailsUTest.java
When respondent links a case, run startAos from new states:
- AwaitingAlternativeService
- AwaitingProcessServerService
- AwaitingDWPResponse
Fixes https://tools.hmcts.net/jira/browse/DIV-6653
Unit test modified
=> DIV-6653: Run startAos for new states

dependency-check-suppressions.xml
Updated configuration to enable build pass
=> Updates to fix dependency issue

build.gradle, dependency-check-suppressions.xml
Fixing dependency vulnerabilities.
=> Fixing dependency vulnerabilities

charts/div-cos/values.preview.template.yaml, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/AosOverdueTest.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/CcdEvents.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/alternativeservice/AlternativeServiceType.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/event/domain/AosOverdueForAlternativeMethodCaseEvent.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/event/listener/AosOverdueEventListener.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/AosService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/AosServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/aos/MarkCasesAsAosOverdueTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/aos/AosOverdueForAlternativeServiceCaseWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/event/listener/AosOverdueEventListenerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/aos/AosOverdueTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/AosServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/aos/MarkCasesAsAosOverdueTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/aos/AosOverdueForAlternativeServiceCaseWorkflowTest.java
Extending the AOS overdue job to also handle cases served by alternative method.
=> DIV-6643: Extending the AOS overdue job (alternative method)

build.gradle
Hopefully, this should fix vulnerability issues.
=> Upgrading guava

src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/AosOverdueTest.java
=> Increase AOS Overdue time

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/DecreeNisiRefusalDocumentGeneratorTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/PopulateDocLink.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorDnFetchDocWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/AddMiniPetitionDraftTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/DecreeNisiRefusalDocumentGeneratorTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/DocumentGenerationTaskTest.java
=> DIV-6189: Small improvements

src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/aospack/offline/IssueAosPackOfflineWorkflowTest.java
=> Fixing Sonar issue

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CourtOrderDocumentsUpdateServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/callback/CourtOrderDocumentsUpdateCallbackTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CourtOrderDocumentsUpdateServiceImplTest.java, src/test/resources/jsonExamples/payloads/updateCourtOrderDocuments.json
Added Decree Nisi and Decree Absolute.
=> DIV-6739: Re-generating Decree Nisi and Decree Absolute

build.gradle, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CourtOrderDocumentsUpdateServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/callback/CourtOrderDocumentsUpdateCallbackTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CourtOrderDocumentsUpdateServiceImplTest.java, src/test/resources/jsonExamples/payloads/updateCourtOrderDocuments.json
This includes the re-generation of costs order. I thought it would be worth having a separate PR and reviews for this.
Functional and unit tests.
=> DIV-6734: Re-generating costs order document

build.gradle
=> Fixing dependency issues

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/EditBulkCaseListingTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/nightly/pipeline/RemoveCaseFromListingTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cos/CosApiClient.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkCaseController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/ListForPronouncementDocGenerationWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkCaseControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/EditBulkCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/ListForPronouncementDocGenerationWorkflowTest.java
Idea here is to divert calls that have parameters set in CCD-definitions to this endpoint. After a month or so with use in the old endpoint, I think we can safely remove it for good.
=> DIV-6740: Creating exclusive endpoint for 'editBulkCase' event

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerUpdateNotificationsEmailTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SendPetitionerEmailNotificationWorkflow.java
We want to have more logs to debug if anything goes wrong.
=> Added more logs to endpoint /petition-updated

build.gradle
https://tools.hmcts.net/jira/browse/DIV-6746
Build failing, issue seems to be similar to fix in https://github.com/hmcts/div-document-generator-client/pull/413.
Updating COS library version also.
=> DIV-6746: Updating serenity version

charts/div-cos/Chart.yaml, charts/div-cos/values.yaml
Hopefully, this will make the secret containing the app insights key available to the chart.
https://tools.hmcts.net/jira/browse/DIV-6801
=> Making app insights instrumentation key available to chart.

charts/div-cos/values.aat.template.yaml
=> Removing app insight info for AAT

src/main/resources/bootstrap.yaml
=> Add secret mapping for app insights key

charts/div-cos/values.demo.template.yaml
Removing app insights id from charts value.
=> DIV-6801: Removing app insights id from charts value

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/ControllerUtils.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/AllowShareACaseWorkflow.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorSubmissionWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/util/ControllerUtilsTest.java
Improving logs to help in diagnosing demo issue.
=> DIV-6800: Improving logs

build.gradle, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendDaRequestedNotifyRespondentEmailTask.java
=> dependencies and checkstyle

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java
=> DIV-6800: Throwing exception that helps us identify case id.

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/task/generics/SendEmailTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/CaseDataExtractor.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/task/generics/SendEmailTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RespondentAOSSubmissionNotificationEmailITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/CaseDataExtractorTest.java
https://tools.hmcts.net/jira/browse/DIV-6770
little refactoring and regression tests
=> DIV-6770: refactoring and regression tests

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorSubmissionWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerSubmissionNotificationEmailTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorSubmissionWorkflowTest.java
AC 3 and 4 (regression tests):
https://tools.hmcts.net/jira/browse/DIV-6819
=> DIV-6819: better regression tests - before implementation

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/CcdFields.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java
- added endpoint for judge costs decision setting a field to `Yes`
https://tools.hmcts.net/jira/browse/DIV-6630
=> DIV-6630: endpoint for judge costs decision

build.gradle
Bumping up div-common-lib: New mappings added for 2 new fields to be accessible from the frontends.
Fixes https://tools.hmcts.net/jira/browse/DIV-5463
=> Bumping up div-common-lib

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/SolicitorPersonalServiceCallbackTest.java, src/integrationTest/resources/fixtures/issue-petition/solicitor-petition.json, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/SolicitorCallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/SolicitorService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/SolicitorServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/IssuePersonalServicePackWorkflow.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/ValidateForPersonalServicePackWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/SolicitorCallbackControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/SolicitorServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/IssuePersonalServicePackWorkflowTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/ValidateForPersonalServicePackWorkflowTest.java
Removing solicitor personal service letter generation
[RPET-269](https://tools.hmcts.net/jira/browse/RPET-269)
=> RPET-269 remove generation of solicitor personal service letter

src/main/resources/bootstrap.yaml
=> Fixing typo

build.gradle, job-scheduler/build.gradle, src/integrationTest/resources/example-application-local.properties
The used version of lombok doesn't work with 2020 version of intellij and junit was too old, I did the minor spring boot upgrade to update junit version from spring boot to something compatible
=> Fix running tests in recent intellij

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/PopulateDocLinkTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorDnFetchDocWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/TestConstants.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SolicitorDnFetchDocTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/PopulateDocLinkTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorDnFetchDocWorkflowTest.java
Allow to proceed when bailiff is successful
Fixes https://tools.hmcts.net/jira/browse/DIV-6089
Unit and functional tests
=> Div 6089: Allow to proceed when bailiff is successful

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/GetPetitionIssueFeesTest.java
=> add service auth token

build.gradle
+ https://nvd.nist.gov/vuln/detail/CVE-2021-21295
=> Bump up io.netty to v 4.1.60

src/integrationTest/resources/fixtures/issue-petition/solicitor-petition.json
I'm just reverting the test file to represent a non-digital solicitor. I had to change this to digital solicitor because, otherwise, the callback (that pointed to AAT) would have failed before the previous commit's changes were deployed to AAT.
Integration tests.
=> DIV-6844: Reverting test file

build.gradle
=> Reverting to old spring boot version

src/contractTest/resources/application.yml
=> update pact test config

build.gradle, charts/div-cos/values.aat.template.yaml, charts/div-cos/values.demo.template.yaml, charts/div-cos/values.preview.template.yaml, src/contractTest/resources/application.yml, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/CcdFields.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/Features.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/BailiffServiceApplicationDataTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/ServiceApplicationDataTask.java, src/main/resources/application.yml, src/main/resources/example-application-aat.yml, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/servicejourney/MakeServiceDecisionTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/BailiffServiceApplicationDataTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/ServiceApplicationDataTaskTest.java, src/test/resources/application.yml
We need to be able to filter by last service application type, but complex type is not working as expected.
Ticket: https://tools.hmcts.net/jira/browse/DIV-6874
Needs ccd PR to be merged:
https://github.com/hmcts/div-ccd-definitions/pull/814
=> DIV-6874: Populate LastServiceApplicationType

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/ccd/BailiffServiceApplication.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/ccd/DivorceServiceApplication.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/BailiffServiceApplicationDataExtractor.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/BailiffServiceApplicationDataTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/BailiffServiceApplicationRemovalTask.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/BailiffOutcomeTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/BailiffServiceApplicationDataExtractorTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/BailiffServiceApplicationDataTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/BailiffServiceApplicationRemovalTaskTest.java
https://tools.hmcts.net/jira/browse/DIV-6852
Ensure that the BailiffApplicationGranted is added to the Bailiff complex type collection
Unit tests
=> DIV-6852: Add BailiffApplicationGranted to collection

charts/div-cos/Chart.yaml
Upgrading to latest version of [chart-java (3.4.5)](https://github.com/hmcts/chart-java/releases/tag/v3.4.5)
https://tools.hmcts.net/jira/browse/RPET-921
platform operations upgrade
=> RPET-921-chart-java-bump

src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/AosSolicitorNominatedCallbackTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/GetPetitionIssueFeesTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/SolicitorCreateAndUpdateTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/SolicitorLinkCaseCallbackTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/SolicitorPersonalServiceCallbackTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/IntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/AosOverdueTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/LinkRespondentTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/SolicitorAmendPetitionForRefusalTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/SubmitRespondentAosBailiffCaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/SubmitRespondentAosCaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/CcdClientSupport.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/CcdSubmissionSupport.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CreateAmendPetitionDraftForRefusalFromCaseIdTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CreateNewAmendedCaseAndSubmitToCCDWorkflow.java
=> Small refactoring job

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendDaRequestedNotifyRespondentEmailTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/PartyRepresentationChecker.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DecreeAbsoluteRequestedRespondentNotificationTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendDaRequestedNotifyRespondentEmailTaskTest.java
For Apply DA resp sol shouldn't be sent email if their are not digital.
Story:
https://tools.hmcts.net/jira/browse/DIV-6899
=> DIV-6898: Do not send email to resp solicitor when it's not digital

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/ccd/DivorceServiceApplication.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/common/Conditions.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorDnFetchDocWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorDnFetchDocWorkflowTest.java
=> div-6906- Allow Petitioner Solicitor to Progress to DN with service application Bailiff

build.gradle
Bump up elastic search to fix dependency check issues.
=> Bump up elastic search

src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/nightly/pipeline/MakeCaseEligibleForDATest.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/ProcessPbaPaymentAbstractITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SolicitorCreateTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SolicitorDnFetchDocTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SolicitorUpdateTest.java
Adding and modifying functional tests
Fixes https://tools.hmcts.net/jira/browse/RPET-612)
=> RPET-612: Adding and modifying functional tests

src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/nightly/pipeline/MakeCaseEligibleForDATest.java
Modifying expected http status on integration test.
=> Fix integration test expected http status

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/CcdFields.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/AddDnOutcomeFlagFieldTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RemoveDnOutcomeCaseFlagTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SearchAwaitingPronouncementCases.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/RemoveDnOutcomeCaseFlagWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DecreeNisiAboutToBeGrantedTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RemoveDnOutcomeCaseFlagTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/AddDNOutcomeFlagTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RemoveDnOutcomeCaseFlagTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/RemoveDnOutcomeFlagWorkflowTest.java
Added happy path functional test.
Fixes https://tools.hmcts.net/jira/browse/RPET-600
=> RPET-600: spring functional test happy path for endpoint: /remove-dn-outcome-case-flag

src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cos/CosApiClient.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RemoveLegalAdvisorMakeDecisionFieldsTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/RemoveLegalAdvisorMakeDecisionFieldsWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RemoveLegalAdvisorMakeDecisionFieldsTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RemoveLegalAdvisorMakeDecisionFieldsTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/RemoveLegalAdvisorMakeDecisionFieldsWorkflowTest.java
More and better tests for the endpoint
=> RPET-601: more tests for /remove-la-make-decision-fields 

src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/decreeabsolute/DaAboutToBeGrantedDocumentsGenerationTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/decreeabsolute/DaAboutToBeGrantedTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/decreeabsolute/DecreeAbsoluteRequestedRespondentNotificationTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/decreeabsolute/ValidateDaTest.java
Story:
https://tools.hmcts.net/jira/browse/RPET-606
=> RPET-606: added mocked tests for /validate-da-request

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/SolicitorCallbackController.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/CalculateSeparationFieldsITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/ClarificationSubmittedTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DnPronouncedNotificationTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/GenerateCoRespondentAnswersITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/MakeCaseEligibleForDASubmittedTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/MockedFunctionalTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/PetitionerClarificationNotificationITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RemoveDnOutcomeCaseFlagTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RemoveLegalAdvisorMakeDecisionFieldsTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RespondentAOSSubmissionNotificationEmailITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/aospack/PostServicePackTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/callback/CaseListedForHearingCallbackTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/callback/CourtOrderDocumentsUpdateCallbackTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/callback/DaGrantedCallbackTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/decreeabsolute/DaAboutToBeGrantedDocumentsGenerationTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/decreeabsolute/DaAboutToBeGrantedTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/decreeabsolute/DecreeAbsoluteRequestedRespondentNotificationTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/decreeabsolute/ValidateDaTest.java
Story:
https://tools.hmcts.net/jira/browse/RPET-607
=> RPET-607: tests for POST /handle-post-personal-service-pack

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/SolicitorCallbackController.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/SolicitorCallbackControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RetrievePbaNumbersITest.java
Story:
https://tools.hmcts.net/jira/browse/RPET-608
=> RPET-608: refactoring and tests

README.md
=> Check if Jenkins builds demo from demo branch

build.gradle, src/contractTest/java/uk/gov/hmcts/reform/divorce/orchestration/client/referencedata/PbaClientConsumerTest.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/PbaValidationClient.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RetrievePbaNumbersITest.java
Change to RefData PBA client to pass email address in header. Updated tests including Pact
[https://tools.hmcts.net/jira/browse/DFR-151]
=> Dfr 151 update ref data pba calls

build.gradle, charts/div-cos/Chart.yaml, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/MockedFunctionalTest.java
Fix elasticsearch vulnerability
DFR-519
- [x ] Bug fix (non-breaking change which fixes an issue)
=> DFR-519: Fix elasticsearch vulnerability

dependency-check-suppressions.xml
Suppress Jakarta el vulnerability
DFR-522
- [x ] Bug fix (non-breaking change which fixes an issue)
=> DFR-522: Suppress Jakarta el vulnerability

Jenkinsfile_CNP, src/contractTest/java/uk/gov/hmcts/reform/divorce/orchestration/client/ccd/AssignCaseAccessConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/divorce/orchestration/client/ccd/CaseRoleConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/divorce/orchestration/client/referencedata/RefDataExternalOrganisationsConsumerTest.java
Add new contract tests
DFR-48
- [x ] New feature (non-breaking change which adds functionality)
=> DFR-48: Add new contract tests

build.gradle, job-scheduler/build.gradle, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationController.java
Reverts hmcts/div-case-orchestration-service#1476
=> Revert "DFR-62 Use latest div-common-lib"

infrastructure/state.tf
=> Adding Azuread version to state.tf file

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CopyPetitionerSolicitorDetailsTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CreateAmendPetitionDraftForRefusalFromCaseIdTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CreateAmendPetitionDraftForRefusalTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CreateAmendPetitionDraftTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetAmendedCaseIdTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SolicitorSubmitCaseToCCDTask.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/ValidateCaseDataTask.java
DFR-62 : Improve logging
Add logging which includes the cas ref
https://tools.hmcts.net/jira/browse/DFR-62
=> DFR-62 : Improve logging

config/fortify-client.properties
DFR-736: update-fortify-releaseid
=> DFR-736: update-fortify-releaseid

src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DnDecisionMadeCallbackITest.java
Fix to integration test class which was intermittently failing
https://tools.hmcts.net/jira/browse/DFR-716
Running integration tests on jenkins and locally - no change to main code.
=> DFR-716: Fix intermittent Itest failures

src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DnDecisionMadeCallbackITest.java
=> Dfr 716 2.0

build.gradle, charts/div-cos/Chart.yaml, dependency-check-suppressions.xml, job-scheduler/build.gradle
=> update dependencies & suppressions

charts/div-cos/Chart.yaml
=> bump chart version

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerCoENotificationEmailTask.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/TestConstants.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/CaseLinkedForHearingTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/DatesDataExtractorTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerCoENotificationEmailTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendRespondentCoENotificationEmailTaskTest.java, src/test/resources/jsonExamples/payloads/caseListedForHearingWelsh.json
=> DFR-613: Certificate of entitlement template change

dependency-check-suppressions.xml
=> Suppressing Jackson

src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/AosIssueBulkPrintWorkflow.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/AosIssueBulkPrintWorkflowTest.java
=> DFR-949: Fix Issue AOS pack for non represented respondents

build.gradle, dependency-check-suppressions.xml, job-scheduler/build.gradle
Bumping PostgreSQL to 42.2.25
Fixes CVE-2022-21724
=> Bumping PostgreSQL

charts/div-cos/Chart.yaml, charts/div-cos/values.yaml
https://tools.hmcts.net/jira/browse/DTSSE-1395
=> Autoscaling

src/integrationTest/resources/fixtures/bulk-list/bulk-create.json
=> Adding the most upto date Data set for the Bulk Create JSON

dependency-check-suppressions.xml, src/contractTest/resources/application.yml, src/integrationTest/resources/fixtures/retrieve-aos-case/aos-divorce-session.json, src/integrationTest/resources/fixtures/retrieve-case/divorce-session.json, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/DocumentGenerationTask.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DnPronouncedDocumentsGenerationITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DocumentGenerationITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/EditBulkCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/MockedFunctionalTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/PrepareToPrintForPronouncementTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RespondentSolicitorNominatedITest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/UpdateBulkCaseHearingDetailsTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/aospack/offline/IssueAosPackOfflineTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/cases/RemoveListingTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/decreeabsolute/DaAboutToBeGrantedDocumentsGenerationTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/decreeabsolute/DaAboutToBeGrantedTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/CtscContactDetailsDataProviderServiceTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/DocumentGenerationTaskTest.java, src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/MultipleDocumentGenerationTaskTest.java, src/test/resources/application.yml, src/test/resources/jsonExamples/expectedCourts.json
https://tools.hmcts.net/jira/browse/DFR-1097
=> Dfr 1097 paremeterise ctsc work hours

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DFR-1625
=> DFR-1625 update jenkins callbacks

charts/div-cos/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSSE-2798
=> Update Java Chart

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DFR-1808
=> DFR-1808 update dependencycheck version

charts/div-cos/Chart.yaml, dependency-check-suppressions.xml
=> Fix dependency issues

dependency-check-suppressions.xml
=> fix suppressions to fix master pipeline

build.gradle
=> Fix cve issue

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/DTSSE-2451
=> Create Postgres 14 flexserver instance

infrastructure/main.tf
=> Changed DB name to div_scheduler

Jenkinsfile_CNP, Jenkinsfile_nightly, build.gradle, charts/div-cos/Chart.yaml, charts/div-cos/values.preview.template.yaml, charts/div-cos/values.yaml, dependency-check-suppressions.xml
=> Point to new DB v14

README.md, dependency-check-suppressions.xml
=> Master failing, test PR Update README.md

dependency-check-suppressions.xml, infrastructure/main.tf
https://tools.hmcts.net/jira/browse/DTSSE-2451
As part of postgres update, remove old DB and creds from vault.
=> Clean up old PG database

infrastructure/main.tf
=> remove old DB Update main.tf

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/DTSSE-2451
=> Remove old DB main.tf

build.gradle
https://tools.hmcts.net/jira/browse/DFR-3850
Update dependencies to Azure Artifacts versions
=> DFR-3850: Update dependencies to Azure Artifacts versions
