hmcts/div-case-orchestration-service

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/RetrieveCaseTest.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationController.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/helper/GlobalExceptionHandler.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationControllerTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/helper/GlobalExceptionHandlerUTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RetrieveCaseITest.java
Prevents an issue where raw string is appending to body of HTTP response when header is set to `application/json`. Added case for 300 (duplicates) HTTP status to ensure body is empty and doesn't cause issues for clients.
Fixes # DIV-3644
Integration / unit tests
* Hardware:
* JDK:
> DIV-3644 fix multiple cases exception handling (300)

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/PetitionIssueTest.java
- src/integrationTest/resources/fixtures/issue-petition/ccd-callback-aos-invitation-service-centre.json
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CcdCallbackWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/PetitionIssuedITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CcdCallbackWorkflowTest.java
This is because the only time AosInvitation letter needs to be generated is when allocated to CTSC court for now, for 5.0.0.
For now, only _beta role users should be able to see the AosInvitation generated.
Only CTSC court members should be given this permission.
However, _beta caseworkers should still be able to progress old, non CTSC cases. In this case, the aosInvitation letter should still not be generated. So we are conditionally generating the Invitation letter when court is CTSC for now.
Paper side AosInvitation will be dealt with in future sprint.
> Only generate aosPetition when divorce unit is serviceCentre

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseMaintenanceClient.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UnlinkRespondent.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateRespondentDetails.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/LinkRespondentWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/LinkRespondentIdamITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UnlinkRespondentUTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateRespondentDetailsUTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/LinkRespondentWorkflowUTest.java
Rolled back user permission  when update respondent data failed.
- [x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* Hardware:
* JDK:
> Remove respondent permission in case update data fails

- src/integrationTest/resources/fixtures/maintenance/submit-aos/aos-defend-consent.json
- src/integrationTest/resources/fixtures/maintenance/submit-aos/aos-defend-no-consent.json
- src/integrationTest/resources/fixtures/maintenance/submit-aos/aos-no-defend-consent.json
- src/integrationTest/resources/fixtures/maintenance/submit-aos/aos-no-defend-no-consent.json
- src/integrationTest/resources/fixtures/respond-to-a-divorce/ccd-callback-aos-submitted-error.json
- src/integrationTest/resources/fixtures/respond-to-a-divorce/ccd-callback-aos-submitted.json
- src/kubernetes/config.aat.yaml
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/ccd/AosCaseData.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitAosCase.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SendRespondentSubmissionNotificationWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RespondentAOSSubmissionNotificationEmailITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SubmitAosCaseITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitAosCaseUTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SendRespondentSubmissionNotificationWorkflowTest.java
- src/test/resources/jsonExamples/payloads/defendedDivorceAOSMissingCaseId.json
- src/test/resources/jsonExamples/payloads/defendedDivorceAOSMissingFields.json
- src/test/resources/jsonExamples/payloads/respondentAcknowledgesServiceDefendingDivorce.json
- src/test/resources/jsonExamples/payloads/respondentAcknowledgesServiceNotDefendingDivorce.json
- src/test/resources/jsonExamples/payloads/undefendedDivorceAOSMissingFields.json
Also removed references to respAdmitOrConsentToFact for now as it's not currently valid
Fixes #DIV-3840  and #DIV-3829
> DIV-3840 - renamed respDefendsDivorce to respWillDefendDivorce

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseMaintenanceClient.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/PopulateExistingCollections.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/UpdateToCCDWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/UpdateCaseTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/PopulateExistingCollectionsUTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/UpdateToCCDWorkflowTest.java
Adds a new task to the UpdateCcdCase workflow called PopulateExistingCollections.
Currently this retrieves a case from CCD with the passed in caseId and auth token. Then the existing payments list will be added to an existingPayments field on the divorceSession for the Mapper to handle when transforming the session.
> Populate existing payments before updating

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cos/CosApiClient.java
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cos/DraftsSubmissionSupport.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationController.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/EmailNotification.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SaveDraftWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/EmailNotificationTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SaveDraftWorkflowTest.java
[DIV-2130](https://tools.hmcts.net/jira/browse/DIV-2130)
This changes the saveDraft call to use a boolean value as the request param instead of the actual email, so it won't be exposed.
The  email will be sent using the request body email value instead.
Unit, end to end and manual testing.
> Use Boolean Query param instead of email

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/PetitionIssueCallBackE2ETest.java
Test was originally disabled since it could not run in the CNP pipeline
until the COS implementation was on master.
DIV-3941
> DIV-3941 enable ignored test

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/SubmitCoRespondentAosCaseTest.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitCoRespondentAosCase.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitCoRespondentAosCaseUTest.java
https://tools.hmcts.net/jira/browse/DIV-4390
Details
Type: Bug
Status:IN TEST  (View Workflow)
Priority: Medium
Resolution: Unresolved
Affects Version/s:
DIV_5.3.0
Fix Version/s:
DIV_5.3.0
Component/s: None
Labels:
Co-Respondent
Steps Taken:
1. Create a Adultery Case. Issue the case initially and reject the case in CCD.
2. Now the case in Rejected Case
3. Now issue the case will generate the AOS and AOS pack for co-respondent.
Expected Behaviour:
Need to identify what page should show. It should be some thing like Progress bar page.
This progress bar page should show based on Case Status in CCD.
Need to identify the stories - what kind of progress bar should should based on the CCD status.
Actual Behaviour:
currently irrespective with the Rejected status this is showing Linking page when …
> Added missing states for CoResp submission

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/task/DefaultTaskContext.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/task/TaskContext.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CaseFormatterAddDocuments.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CoRespondentLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/PetitionGenerator.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RespondentLetterGenerator.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/task/DefaultTaskContextTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CaseFormatterAddDocumentsTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CoRespondentLetterGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/PetitionGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RespondentLetterGeneratorTest.java
[Make generic documents generated handler in COS](https://tools.hmcts.net/jira/browse/DIV-4688)
- Make the CaseFormatterAddDocuments task reusable by adding the
document collection to the task context so documents can be added to it in
different document generator tasks.
> Pre-factor for Generic document task

- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/IntegrationTest.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/config/HttpConnectionConfiguration.java
- src/test/resources/logback-test.xml
It's causing more than 1 million log messages in production
https://github.com/hmcts/java-logging/blob/master/java-logging-httpcomponents/src/main/java/uk/gov/hmcts/reform/logging/httpcomponents/OutboundRequestLoggingInterceptor.java#L41
Also reduced test loggin to WARN
Before:
After:
Fixes #DIV-3956
> [PREVIEW] DIV-3956 - reduced logging noise

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/DnSubmittedEmailNotificationTask.java
[DIV-4717](https://tools.hmcts.net/jira/browse/DIV-4717)
Logging the caseId instead of petitioner email, so personal data is not identifiable from the logs alone.
> Remove personal identifier from logging

- build.gradle
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/GetCaseWithId.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/GetCaseWithIdWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/GetCaseWithIdWorkflowTest.java
Note: This is a temporary measure to stop div-alert spam for false positive failed payment-update calls.
Despite having a successful payment and update in CCD to the correct state, on rare occasions the strategic payment callback is still incorrectly triggered on that case, resulting in a 422. This triggers an Azure alert via email to Developers.
The error is a non-issue since as far as the user and caseworkers are concerned, the case has been moved on correctly.
However this issue does spam Devs with email notifications and also pollutes the appInsights logs.
The proper fix is for payments team to investigate and resolve the issue with callbacks triggering on successful payment status checks, however this PR is a quick measure to stop triggering updates when the case is already moved. …
> Don't do payment update when case state is not AwaitingPayment

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SendRespondentSubmissionNotificationWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RespondentAOSSubmissionNotificationEmailITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SendRespondentSubmissionNotificationWorkflowTest.java
- src/test/resources/jsonExamples/payloads/respondentAcknowledgesServiceNotDefendingNotAdmittingDivorce.json
When respondent chooses not to defend the divorce but not admit, we
should send them a confirmation email as we do for other responses
Fixes #DIV-4841
> DIV-4841 - handle NoNoAdmission response in resp notification email task

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/IntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/LinkRespondentTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/SubmitRespondentAosCaseTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cos/CosApiClient.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/GetInconsistentPaymentInfo.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerCoRespondentRespondedNotificationEmail.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendRespondentSubmissionNotificationForDefendedDivorceEmail.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetCoRespondentAnswerReceived.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetCourtDetails.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetIssueDate.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitRespondentAosCase.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateRespondentDetails.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/CcdUtil.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SendCoRespondSubmissionNotificationWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/CoRespondentAnswerReceivedITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/LinkRespondentIdamITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/PetitionIssuedITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RetrieveDraftITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SolicitorCreateITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SubmitRespondentAosCaseITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/GetInconsistentPaymentInfoUTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendRespondentSubmissionNotificationEmailTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetCoRespondentAnswerReceivedTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetCourtDetailsTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetIssueDateTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitRespondentAosCaseUTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateRespondentDetailsUTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/util/CcdUtilUTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SendCoRespondSubmissionNotificationWorkflowTest.java
- Removed dependency on the Joda-Time library
- Replaced with native Java 8 clock-based implementation, injected as a dependency where required.
- This approach allows an alternate clock e.g. one fixed at a desired date to be used during testing.
Ran the full functional test suite due to the great number of classes affected.
> DIV-4789: Replace Joda-Time with native Java DateTime based on Clock

- build.gradle
- charts/div-cos/values.aat.template.yaml
- charts/div-cos/values.preview.template.yaml
- infrastructure/aat.tfvars
- infrastructure/main.tf
- infrastructure/preview.tfvars
- infrastructure/variables.tf
To prevent hammering AAT, as every `/health` call checks _every_ dependent service, generating sometimes ~30 subsequent calls (e.g COS)
Tested locally via
`MANAGEMENT_ENDPOINT_HEALTH_CACHE_TIMETOLIVE=60000 ./gradlew clean bootrun`
> Override Spring's management endpoint cache to 30 seconds in AAT

- build.gradle
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendCoRespondentGenericUpdateNotificationEmail.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerUpdateNotificationsEmail.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CaseLinkedForHearingWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendCoRespondentNotificationEmailTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerNotificationEmailTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CaseLinkedForHearingWorkflowTest.java
https://tools.hmcts.net/jira/browse/DIV-4906
Simply triggers a generic email to the co-resp (if they exist) when a case is listed for hearing (COE) telling them that something has changed with the relevant divorce case
Tested using swagger at http://div-cos-pr-276.service.core-compute-preview.internal/swagger-ui.html#!/callback45controller/caseLinkedForHearingUsingPOST
> DIV-4906: Updated COE workflow to trigger generic email to Coresp

- build.gradle
- ruleset.xml
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/AosReceivedCallbackTest.java
Previously the Gradle build would be polluted with hundreds of lines of warnings about migration of rulesets to new files. This change migrates to the new rulesets and also carries over the rule exclusions that we have. This makes the build output far more readable.
Fixes # 
[DIV-4835 Fix PMD/checkstyle warnings](https://tools.hmcts.net/jira/browse/DIV-4835)
Reduce log pollution
Run command 
```bash
./gradlew clean build
```
from project directory and check build output for occurrence of ruleset migration messages.
> DIV-4835 Fix PMD/checkstyle warnings on gradle build

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerUpdateNotificationsEmail.java
Fixes all the 500 errors we're getting on production for http://div-cos-prod.service.core-compute-prod.internal/petition-updated
We were trying to use getMandatoryPropertyValueAsString() on a field that is not always populated with data
> Fix 500 error on Production due to missing mandatory field

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/UpdateBulkCaseDnPronouncementDateTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cos/CosApiClient.java
- src/integrationTest/resources/application.properties
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkCaseController.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetCourtHearingDetailsFromBulkCase.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetDnGrantedDate.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/CcdUtil.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/DateUtils.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/UpdateBulkCaseDnPronounceWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkCaseControllerTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/UpdateBulkCaseDnPronouncementDateITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetDnGrantedDateTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/util/CcdUtilUTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/UpdateBulkCaseDnPronounceWorkflowTest.java
[DIV-4827](https://tools.hmcts.net/jira/browse/DIV-4827)
When DN Pronouncement event is triggered on the bulk case, this will trigger a callback that sets the DecreeNisiGrantedDate field to be equal to the hearingDate filed (but only date component, ignoring the time).
It will also set the DAEligibleFromDate field (set six weeks and 1 day from the DecreeNisiGrantedDate) so it can be easily used by the next story to update all individual cases within the bulk case with the same data.
Automated tests
> DIV-4827 DN Pronouncement Date Calculations

- src/integrationTest/resources/fixtures/bulk-list/bulk-update-listing.json
Recent change of CourtName to FixedList type broke this test.
> Changed CourtName json value to valid FixedList enum

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DnPronouncedDocumentsGenerationITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java
[DIV-4831](https://tools.hmcts.net/jira/browse/DIV-4831)
New requirement to generate costs orders even in No scenario. When CostsClaimGranted is set, it'll either be Yes or No. If its not set, it will be null.
> DIV-4831: Generate Costs Order as long as CLAIM_COSTS_GRANTED field is set

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/SubmitDaCaseTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cos/CosApiClient.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseFormatterClient.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationController.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/FormatDivorceSessionToDaCaseData.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SubmitDaCaseWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationControllerTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SubmitDaCaseITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/FormatDivorceSessionToDaCaseDataTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SubmitDaCaseWorkflowUTest.java
[DIV-5111](https://tools.hmcts.net/jira/browse/DIV-5111)
Adds a new endpoint `/submit-da` for Decree Absolute submissions in line with existing endpoints:
`/submit-aos` and `/submit-dn`
This one is more bare since we currently don't require adding any additional case data into the case, simply the case state needs to be progressed. However, the workflow means it can be updated with a formatter in the future as needs be.
Automated, Integration and Manual Testing.
> DIV-5111 Add Submit DA Endpoint

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DnPronouncedDocumentsGenerationITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java
…en endClaim
[DIV-5176](https://tools.hmcts.net/jira/browse/DIV-5176)
When the Petitioner chooses to no longer continue with costs, it sets the DN costs Option field to 'endClaim', otherwise it can be a numerous selection of options.
If the field is not set (null) then the petitioner claims costs field from PFE takes priority.
So this PR just doesn't generate Costs Order when DNOption is endClaim.
* Hardware:
* JDK:
> DIV-5176: Add conditional that won't generate costs order if Petitioner has chosen endClaim

- Jenkinsfile_CNP
- build.gradle
[DIV-5278](https://tools.hmcts.net/jira/browse/DIV-5278)
This PR adds two configurations to the wiremockFunctional task so up to date test results won't prevent re-run of the tests, and to also display the full standard logs.
Also exposes the Junit Test Results to Jenkins.
* Hardware:
* JDK:
> Disable local test caching and show standard test logs

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/MakeCaseEligibleForDAWorkflowTest.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/task/DefaultTaskContext.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SearchDNPronouncedCasesTest.java
-- use Awaitility to make the integration test 'MakeCaseEligibleForDAWorkflowTest' more reliable
-- removed annotations such as 'Builder' and 'AllArgsConstructor` for `DefaultTaskContext` as the object itself is not immutable by design 
-- unit tests
-- integration tests
> Div 5238 search scheduler job improvements

- infrastructure/main.tf
> Next Monday we will be making a breaking change to cnp-module-postgres
https://github.com/hmcts/cnp-module-postgres/pull/41
> It is to make the `subscription` variable required
any team who have deployed their apps to the `ithc` or `perftest` will have already made this change
>see usage for a full example  of how to pass through the variable: https://github.com/hmcts/cnp-module-postgres#usage
> We are making this change because multiple teams weren't told they needed to do this as part of using new environments, and it gives an error message which is confusing (losing time and frustrating developers), making it a required variable gives a very clear error  message and a very easy update.
> Added required subscription param for cnp-module-postgres

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/SubmitDaCaseTest.java
New callback on endpoint required the DecreeNisiGrantedDate field to be populated.
> Fixed failing da submit test

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/bulk/BulkWorkflowExecutionResult.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/RetryableBulkCaseWorkflow.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/BulkCaseServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/RetryableBulkCaseWorkflowTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/ProcessBulkCaseITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/BulkCaseServiceImplTest.java
[DIV-5346](https://tools.hmcts.net/jira/browse/DIV-5346)
There is an elastic search issue where sometimes a change to the case does not propagate to ES. This means a case already linked to a Bulk Case is sometimes retrieved in the search and there is an attempt to update the Bulk Link, which is not allowed, throwing an error.
This drops cases with a 422 error from the CaseList and CaseAcceptedList.
In case of 422 and missing Bulk Link, the next scheduled query should pick up the case to retry.
In case of 422 and existing Bulk Link, it will be removed from the extra Bulk Link, so that case will only be associated with one Bulk Case.
This does mean a bulk case can potentially end up with less cases than the minimum however.
> Fix for bulk cases in a ElasticSearch stuck state

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/MakeCaseEligibleForDATest.java
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cms/CmsClientSupport.java
- src/integrationTest/resources/application.properties
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
Added a search (timeout set to 40 seconds) to the test case in ElasticSearch via CMS to ensure that indexing is somehow complete and the ES is ready for queries
- Integration Tests
> Improve MakeCaseEligibleForDATest to be more resilient

- build.gradle
The test/index.html is only generated when Unit Tests successfully finish (whether it passes or fails)
This will make the functional tests run only in that case.
Where the unit tests were aborted due to a failure in a parallel pipeline such as DepedencyCheck, this change will stop the wiremockFunctionals from running and wasting time.
This is to avoid wiremock functionals being run by the finally block in Jenkins even when standard unit tests fail. https://github.com/hmcts/cnp-jenkins-library/blob/master/src/uk/gov/hmcts/contino/PipelineCallbacksRunner.groovy#L26
> Only run wiremockFunctional if unit test report was generated

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendDaGrantedNotificationEmail.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendDaRequestedNotifyRespondentEmail.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DecreeAbsoluteAboutToBeGrantedWorkflow.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/NotifyRespondentOfDARequestedWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DecreeAbsoluteRequestedRespondentNotificationTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/DecreeAbsoluteServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendDaGrantedNotificationEmailTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendDaRequestedNotifyRespondentEmailTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DecreeAbsoluteAboutToBeGrantedWorkflowTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/NotifyRespondentOfDARequestedWorkflowTest.java
Previously the CCD case Id was being shown where the D8Familyman reference should of been shown on these emails. This PR is to fix this to show the D8Familyman reference.
https://tools.hmcts.net/jira/browse/DIV-5365
* Hardware:
* JDK:
> fix wrong reference showing in emails

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/SolicitorLinkCaseCallbackTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/CcdSubmissionSupport.java
https://github.com/hmcts/div-ccd-definitions/pull/145 changed the permission of the `aosNominateSol` to be R for caseworker, so the test needed updating to trigger the event using the citizen token (which has CRU) as it is the citizen who usually triggers this event (through RFE)
Fixes pipeline
> Fixed AOS test event to be triggered by citizen's token

- build.gradle
Removes vulnerability failing our builds:
https://nvd.nist.gov/vuln/detail/CVE-2019-7614
> Bumped elasticsearch version to remove vuln failing builds

- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/ScheduleBulkCaseForListingTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/MakeCaseEligibleForDATest.java
Allow Intelli-J test runner to pick up Lombok annotations after Gradle 5 upgrade.
> Amend gradle to allow for lombok

- charts/div-cos/Chart.yaml
Because of chart configuration changes in https://github.com/hmcts/div-case-orchestration-service/pull/448
We need to bump the version number to make sure new changes take effect
Fixes #DIV-5516
> DIV-5516 - bump chart version to 1.2.0

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/dataextraction/FamilyManDataExtractionIT.java
We've realised that one the dates the business deems as mandatory is actually not. I've asked them about how to handle this, but in the meantime this should unblock the pipeline.
The feature is not being used in production yet, so we're not deploying broken software. Rest assured.
- [ X] Bug fix (non-breaking change which fixes an issue)
> Ignoring this test until we get some answers from the business

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeAbsoluteDataExtractor.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DataExtractionFileCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DecreeAbsoluteDataExtractorTest.java
If we don't find a date when the DA was requested, we should use the date is was granted instead.
Unit tests
> Changing fall back date logic

- infrastructure/aat.tfvars
Has been tested on PRs and ready to by demoed on AAT.
This will enable the feature on AAT by default.
> Enable DN Refusal Clarification on AAT by default

- infrastructure/aat.tfvars
- infrastructure/main.tf
- infrastructure/preview.tfvars
- infrastructure/prod.tfvars
- infrastructure/variables.tf
- src/main/resources/application.yml
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DataExtractionEmailClientTest.java
This is about not having test e-mail addresses as default, so that if something goes wrong in the AKS migration, we don't end up sending the prod data to test e-mails.
I'm also addressing a TF variable issue identified by @hosainnet.
- [ x] New feature (non-breaking change which adds functionality)
Integration tests.
> Removing default terraform e-mails and fixing TF variable

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerUpdateNotificationsEmail.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/AosOverdueNotificationTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerUpdateNotificationEmailTest.java
Updates the code so that a specific email is sent when a case is moved to AOS overdue.
Previously, only a generic email was sent.
[DIV-5671](https://tools.hmcts.net/jira/browse/DIV-5671)
- Task test updated to take into account the new states
- Functional tests added
- Integration tests added
> update to send specific email on AOS overdue, rather than generic

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/fees/FeeResponse.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/notification/NotifyForRefusalOrderTask.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/fees/FeeResponseTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DnDecisionMadeCallbackITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/notification/NotifyForRefusalOrderTaskTest.java
Adds public method to FeeResponse to get Fee Amount (double) as a formatted String.
Fails the task if FeeResponse amount is null, as this should not be a valid scenario.
* Hardware:
* JDK:
> Added Formatting for Fee Amount Double

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/DecreeNisiRefusalDocumentGeneratorTask.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DecreeNisiAboutToBeGrantedTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/DecreeNisiRefusalDocumentGeneratorTaskTest.java
[DIV-5098](https://tools.hmcts.net/jira/browse/DIV-5098) 
This PR does the following:
When generating a DN Refusal Order Clarification Document, it checks for existing documents and will change the Document type to 'other' and rename the document with a timestamp.
The new DN Refusal Order document will have the original Document Type and File Name and therefore frontend won't be affected. Caseworkers should be able to tell which document is old vs which is new based on the file name.
* Hardware:
* JDK:
> Keep previous DN Clarification documents

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/aospack/offline/IssueAosPackOfflineWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/aospack/offline/AosPackRespondentOfflineTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/aospack/offline/IssueAosPackOfflineWorkflowTest.java
When issuing AOS Pack offline, for a respondent, the AOS due date is reset to 30 days after the current date.
Fixes [DIV-5555](https://tools.hmcts.net/jira/browse/DIV-5555)
Unit tests and functional tests added
> modify AOS overdue due date

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/DnAboutToBeGrantedTest.java
- src/integrationTest/resources/fixtures/callback/dn-refusal-clarification.json
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/DecreeNisiRefusalDocumentGeneratorTask.java
- src/main/resources/application.yml
- src/main/resources/example-application-aat.yml
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DecreeNisiAboutToBeGrantedTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/DecreeNisiRefusalDocumentGeneratorTaskTest.java
https://tools.hmcts.net/jira/browse/DIV-5098
Previously, the wrong Json Key name (documentType, when DocumentType was expected) was being used for comparison. This meant only the latest document was kept and all previous ones were still being dropped as the condition did not match and returned false.
Updated integration test with previous documents verified it now stores older docs properly.
* Hardware:
* JDK:
> Fixed older clarification documents not being stored properly

- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/dataextraction/FamilyManDataExtractionIT.java
Starting a local SMTP server when running tests locally.
Integration tests.
> DIV-5860: Enabling Integration test for data migration to run with no manual steps

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/SubmitDnCaseTest.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseFormatterClient.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/FormatDivorceSessionToDnCaseData.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitDnCase.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DecreeNisiAboutToBeGrantedWorkflow.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SubmitDnCaseWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DecreeNisiAboutToBeGrantedTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SubmitDnCaseITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/FormatDivorceSessionToDnCaseDataUTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SubmitDnCaseUTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DecreeNisiAboutToBeGrantedWorkflowTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SubmitDnCaseWorkflowUTest.java
[DIV-5766 - Awaiting Clarification For DN Submit](https://tools.hmcts.net/jira/browse/DIV-5766)
When the current case state is in AwaitingClarification, then when the user adds more information and submits on the Decree Nisi frontend, we can reuse the original DN Submit endpoint but trigger a different event based on the case state (AwaitingClarification instead of AwaitingDecreeNisi).
Data will be posted as is: may require mapper change.
* Hardware:
* JDK:
Still requires config change from …
> DIV-5766 Add AwaitingClarification Path in DN-Submit Endpoint

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SearchCasesDAOverdueTask.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/MakeCasesDAOverdueITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SearchCasesDAOverdueTaskTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SearchCasesDAOverdueTest.java
Use right CCD date field when searching for cases are eligible for DA Overdue (i.e. 12 months since DN pronounced )
> DIV-5293 use right CCD field when searching for cases eligible for DA Overdue

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetDnPronouncementDetailsTask.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/CcdUtil.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetDnPronouncementDetailsTaskTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/util/CcdUtilUTest.java
https://tools.hmcts.net/jira/browse/DIV-5849
Adds validation to check if the caseworker is attempting to pronounce the bulk case when the hearing date is in the future, so pronouncement could not have happened yet.
* Hardware:
* JDK:
> Add validation for pronouncement date in the future

- .dependabot/config.yml
This is to add dependabot so that it upgrades the springboot health starter to version 0.0.5 which is recommended for AKS changes being made.
> Add dependabot  config

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformations/D8FormToCaseTransformer.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidator.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/TransformationBulkScanITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/NewDivorceCaseValidatorTest.java
- src/test/resources/jsonExamples/payloads/bulk/scan/fullD8Form.json
- src/test/resources/jsonExamples/payloads/bulk/scan/partialD8Form.json
https://tools.hmcts.net/jira/browse/BSP-91
Added the following 2 fields for Section 4 ('Details of marriage/civil partnership') from the D8 Form.
- D8MarriagePetitionerName
- D8MarriageRespondentName
Both fields are mandatory.
The following transformations were applied:
D8MarriagePetitionerName -> D8MarriagePetitionerName
D8MarriageRespondentName -> D8MarriageRespondentName
> BSP-91: Added D8MarriagePetitionerName and D8MarriageRespondentName fields

- .dependabot/config.yml
Stop us getting spammed daily about new versions - rather than removing it altogether, by setting it to weekly we can still regularly have the latest dependencies without too many PRs or resources being taken up
> Changed dependabot to weekly to stop spam

- build.gradle
Sonarcloud is failing master due to accidentally thinking our bulk scan files have no tests when they actually do. We're adding a suppression to stop development being blocked and will come back to this at a later date to remove the suppression
> [FAST] Added suppression for bulk scan directory to get master green

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/AosPackOfflineCaseValidator.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/AosPackOfflineCaseValidatorTest.java
Fixing a bug where we would accidentally add duplicate error message for a single error for AosOfflinePack validation
- The logic that these 2 if statements should cover is below:
- If RespJurisdictionAgree is 'No',  and RespJurisdictionDisagreeReason is empty, status = warning
- If RespJurisdictionAgree is 'No',  and RespJurisdictionDisagreeReason is not-empty, status = success
- If RespJurisdictionAgree is 'Yes',  and RespJurisdictionDisagreeReason is empty, status = success
- If RespJurisdictionAgree is 'Yes',  and RespJurisdictionDisagreeReason is not-empty, status = warning
- If RespJurisdictionAgree is anything else,  and RespJurisdictionDisagreeReason is empty, status = success
- If RespJurisdictionAgree is anything else,  and RespJurisdictionDisagreeReason is not-empty, status = …
> BSP-120: Fixed duplicate error message appearing from aos validation

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/bulk/scan/BulkScanIntegrationTest.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/BulkScanForms.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformation/AosOffline2YrSepFormToCaseTransformer.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformation/BulkScanFormTransformerFactory.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/AosOffline2yrSepCaseValidator.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/BulkScanFormValidatorFactory.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/UpdateBulkScanITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformation/AosOffline2YrSepFormToCaseTransformerTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/transformation/BulkScanFormTransformerFactoryTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/AosOffline2yrSepCaseValidatorTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/BulkScanFormValidatorFactoryTest.java
- src/test/resources/jsonExamples/payloads/bulk/scan/aos/2yearSeparation/aosOffline2yrSep.json
- src/test/resources/jsonExamples/payloads/bulk/scan/aos/2yearSeparation/invalidAosOffline2yrSep.json
- src/test/resources/jsonExamples/payloads/bulk/scan/aos/5yearSeparation/aosOffline5yrSep.json
- src/test/resources/jsonExamples/payloads/bulk/scan/aos/5yearSeparation/invalidAosOffline5yrSep.json
Because AosPackOffline technically covers 5 forms, we've had to rename the initial AosPackOffline to 'AosOffline2YrSep' as this is the first form from AOS we handle.
> BSP-119: Rename AosPackOffline to 2 Year Separation

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/D8FormValidator.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/scan/validation/D8FormValidatorTest.java
D8PetitionerCorrespondenceUseHomeAddress should be able to accept empty values.
Unit tests.
> BSP-178: Change to D8PetitionerCorrespondenceUseHomeAddress validation

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/config/HttpConnectionConfiguration.java
- src/main/resources/application.yml
Updating maximum number of HTTP connections per REST template to 25. There are two REST templates, one for health check and one for other connections, so total number per COS would be 50 connections.
Default per REST template is 10. Seen quite a lot of timeout exception in PROD logs due to connection poll running out.
* Hardware:
* JDK:
> Hotfix to update max http connections to 25

- build.gradle
Flux needs to be triggered. The release timeout was increased and this might fix the warning we're getting on div-dev.
> Triggering flux

- checkstyle.xml
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetClaimCostsFrom.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorCreateWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetClaimCostsFromTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorCreateWorkflowTest.java
Set the value of claimCostsFrom to respondent (by default) on solicitor journey **if** petitioner is claiming costs, and solicitor has not yet specified a value for claimCostsFrom.
Fixes https://tools.hmcts.net/jira/browse/RPET-62
Unit tests included.
> Rpet 62 respondent unable to dispute costs

- build.gradle
Removed redundant Checkstyle config that initially made the build fail on Checkstyle issues. This is since outdated and has been replaced by the following line: 
“maxWarnings = 0”
> Removed redundant checkstyle config task

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/ExtractedDataPublisher.java
Updated logging so that we're not getting alerts for "failed" data extractors
> Updated logging to not break azure alert

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cos/CosApiClient.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseFormatterClient.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseMaintenanceClient.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/DocumentGeneratorClient.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/FeatureToggleServiceClient.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/FeesAndPaymentsClient.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/PaymentClient.java
- Added @ApiOperation() to all endpoints with a description of what the endpoint does to make out API more clear
- Replaced "@RequestMapping()" with action specific annotation. For example: "method = POST, value = "/dn-submitted")"
> Add API operation annotation to all endpoints to make them clearer

- build.gradle
- dependency-check-suppressions.xml
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- gradlew.bat
Bumped Gradle wrapper from 5.6.3 to 6.5 - this drastically decreases build compilation times so pipeline should be quicker.
Also removed redundant vulnerability suppressions and tidied up build.gradle
> Bump gradle to 6.5, removed redundant vuln suppressions

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CaseLinkedForHearingWorkflow.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SendDnPronouncedNotificationWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CaseLinkedForHearingWorkflowTest.java
The method getDocumentTypes() has been modified to fix an issue seen in the logs. 
The respondent solicitor cover letter was not sent as it was not added to the list of document types 
to print.
Fixes https://tools.hmcts.net/jira/browse/DIV-5622
> DIV-5622: Get Document types method modified to fix error (Respondent solicitor cover letter not sent)

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/CoECoverLetterDataExtractor.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DnPronouncedNotificationTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/AddresseeDataExtractorTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/CoECoverLetterDataExtractorTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/DatesDataExtractorTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/CoERespondentLetterGenerationTaskTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/CoERespondentSolicitorLetterGenerationTaskTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SendDnPronouncedNotificationWorkflowTest.java
as we have 2 fields and it looks like one is used to indicate if cost has been claimed and the other one if it's been granted I decided to rename const we use to make it more descriptive what this actually checks.
More details in this and following comments:
https://tools.hmcts.net/jira/browse/DIV-6317?focusedCommentId=790298&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-790298
> DIV-5622: COST_CLAIMED -> COSTS_CLAIM_GRANTED

- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/CoERespondentCoverLetterGenerationTaskTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/DnGrantedRespondentCoverLetterGenerationTaskTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/DnGrantedRespondentSolicitorCoverLetterGenerationTaskTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SendDnPronouncedNotificationWorkflowTest.java
Address lacking scenarios from sonar:
1. https://sonarcloud.io/component_measures?id=div-case-orchestration-service&metric=new_coverage&pullRequest=866&selected=div-case-orchestration-service%3Asrc%2Fmain%2Fjava%2Fuk%2Fgov%2Fhmcts%2Freform%2Fdivorce%2Forchestration%2Ftasks%2Fbulk%2Fprinting%2FCoERespondentCoverLetterGenerationTask.java&view=list
2. https://sonarcloud.io/component_measures?id=div-case-orchestration-service&metric=new_coverage&pullRequest=866&selected=div-case-orchestration-service%3Asrc%2Fmain%2Fjava%2Fuk%2Fgov%2Fhmcts%2Freform%2Fdivorce%2Forchestration%2Fworkflows%2FSendDnPronouncedNotificationWorkflow.java&view=list
and rename wrongly named methods in unit tests (coRespondent -> respondent)
> DIV-6137: more unit tests and clean up

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SolicitorSubmitCaseToCCDTask.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SolicitorSubmitCaseToCCDTaskTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CreateNewAmendedCaseAndSubmitToCCDWorkflowTest.java
Testing the new functionality of amending a case with a solicitor (for refusal) on swagger, I saw it was failing on the last task: 'update case'. This is because I was sending some case data to that event (as if it needed to update fields also) whereas it should only update the case state.
I updated the previous task to return empty hashmap so that update case only updates the case state
Fixes https://tools.hmcts.net/jira/browse/DIV-6198
> DIV-6198: Call update case with empty case data

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SolicitorSubmitCaseToCCDTask.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CreateNewAmendedCaseAndSubmitToCCDWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SolicitorAmendPetitionForRefusalITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SolicitorSubmitCaseToCCDTaskTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CreateNewAmendedCaseAndSubmitToCCDWorkflowTest.java
I noticed that a function I had in COS (i.e. updating the old case to 'amend petition' state) is already done by the event calling this callback.
Removing that functionality
Fixes https://tools.hmcts.net/jira/browse/DIV-6198
> DIV-6198: Removing 'update case' from workflow

- build.gradle
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/CostOrderCoRespondentCoverLetterGenerationTask.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/ValidationBulkScanITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CostOrderCoRespondentCoverLetterGenerationTaskTest.java
There was an issue on prod sharepoint. The last file couldn't be sent to approve (some issue in sharepoint) and this is why we had to upload this file again and use different name.
Template renamed:
https://github.com/hmcts/rdo-docmosis/pull/327
DGS updated - different template registered:
https://github.com/hmcts/div-document-generator-client/pull/349
When everything is merged we should merge this one as well:
https://github.com/hmcts/rdo-docmosis/pull/334
> using renamed template FL-DIV-LET-ENG-00358 ->FL-DIV-LET-ENG-00358A

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetAmendedCaseIdTask.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CreateNewAmendedCaseAndSubmitToCCDWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SolicitorAmendPetitionForRefusalITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CopyPetitionerSolicitorDetailsTaskTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SetAmendedCaseIdTaskTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/CreateNewAmendedCaseAndSubmitToCCDWorkflowTest.java
A new task is created so that when a case is amended (by a petitioner solicitor), a link to the new amended case is displayed in the 'old' case, under the 'linked cases' tab.
Fixes https://tools.hmcts.net/jira/browse/DIV-6436
> DIV-6198: Setting amended case id in old case when amending case

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerSubmissionNotificationEmailTask.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorSubmissionWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/ProcessPbaPaymentITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SendPetitionerSubmissionNotificationEmailTaskTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorSubmissionWorkflowTest.java
This adds the `sendPetitionerSubmissionNotificationEmailTask` to the 
Solicitor
Event: `solicitorStatementOfTruthPaySubmit`
Endpoint: "CallBackURLAboutToSubmitEvent":"${CCD_DEF_COS_URL}/process-pba-payment",
Email triggered: sendPetitionerSubmissionNotificationEmailTask (if represented)
https://tools.hmcts.net/jira/browse/DIV-6196
> DIV-6196: Add solicitor task to email trigger

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/CcdFields.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/ServiceJourneyServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/MakeServiceDecisionDateTask.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/MakeServiceDecisionDateTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/ServiceJourneyServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/MakeServiceDecisionDateTaskTest.java
Simple mistake - wrong name of field. Should be capitalised. 
https://tools.hmcts.net/jira/browse/DIV-5411
Extracted these 2 new fields from OrchestrationConstants class and this is the very first step to move all Fields names from this huge mistake into a smaller class with clear purpose.
> DIV-5411: rename serviceApplicationGranted -> ServiceApplicationGranted

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/document/ApplicationServiceTypes.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/BasePayloadSpecificDocumentGenerationTask.java
typo "demeed", should be: "deemed"/
Plus a bit better log.
> DIV-6237: fixed typo 'demeed' -> 'deemed', and add better logs

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/BasePayloadSpecificDocumentGenerationTask.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/MakeServiceDecisionTest.java
File name field was not populated and then it was displayed as "null.pdf" in ccd ui.
It was caused because we have used it before only for documents that were sending to bulk printing and never stored in CCD.
New feature should not break anything in bulk printing (if `null` hasn't String should be also fine).
https://tools.hmcts.net/jira/browse/DIV-6237
https://tools.hmcts.net/jira/browse/DIV-6238
> DIV-6237: populate name of newly created file

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/task/generics/SendEmailTask.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/CaseDataExtractor.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/emails/DeemedApprovedEmailTask.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/emails/DispensedApprovedEmailTask.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/servicejourney/ServiceDecisionMadeWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/CaseDataExtractorTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/emails/DeemedApprovedEmailTaskTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/emails/DispensedApprovedEmailTaskTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/servicejourney/ServiceDecisionMadeWorkflowTest.java
There is an edge case with cases where petitioner email is null or `""`. Then we shouldn't even try to send email.
Story
https://tools.hmcts.net/jira/browse/DIV-6489
> DIV-6489: when empty email - don't try to send

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorDnFetchDocWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SolicitorDnFetchDocWorkflowITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorDnFetchDocWorkflowTest.java
When triggering the event "Draft Decree Nisi Application", a callback is called to query the respondent answers document so that it can be displayed on the first page of the event workflow.
Currently, when this document is not present, an error is raised.
Not query respondent answers document for deemed or dispensed approved
Fixes https://tools.hmcts.net/jira/browse/DIV-6094
> DIV-6094: Not query respondent answers document for deemed or dispensed approved

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/generalorders/GeneralOrderGenerationTask.java
document type in CCD is:
```
{
"LiveFrom": "27/08/2020",
"ID": "d8documentsReceivedEnum",
"ListElementCode": "GeneralOrder",
"ListElement": "General Order"
}
```
> DIV-6142: generalOrder -> GeneralOrder

- build.gradle
- job-scheduler/build.gradle
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/job/AosOverdueJob.java
The job was not being instantiated because it didn't have a no-args constructor.
The next PR will write tests to make sure that this is spotted early on if we ever do this again.
Existing tests. New tests will be written in the next PR.
> DIV-6441: Scheduler fix

- charts/div-cos/Chart.yaml
- charts/div-cos/values.yaml
This being on by default means that staging pods are listed as quartz agents. That can be a problem because there's always going to be an old staging pod (as we only use 1 of 2 clusters) and we might be running the scheduler with unintended code.
If we want to test the scheduler before the pipeline, we can always turn it on in the PR environment.
For other environments, the configuration will live in Flux.
This should only be merged when https://github.com/hmcts/cnp-flux-config/pull/5978 is merged.
Will be checked manually in AAT and staging.
> DIV-6441: Making decision to enable scheduler not a default one

- charts/div-cos/values.preview.template.yaml
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/AosOverdueTest.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/aos/MarkAosCasesAsOverdueTask.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/CMSElasticSearchSupport.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/CaseOrchestrationValues.java
- src/main/resources/application.yml
- src/main/resources/example-application-aat.yml
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/aos/AosOverdueTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/aos/MarkAosCasesAsOverdueTaskTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/util/CaseOrchestrationValuesTest.java
- src/test/resources/application.yml
This fix keeps the behaviour exactly as it is in prod until we lower the grace period to zero by the business' request through an environment variable.
I'm also making the preview environment work with zero-days grace period and have the job running every minute to make demoing this easier.
> DIV-6543: Making AOS Overdue grace period configurable

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/CcdEvents.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateRespondentDetails.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/UpdateRespondentDetailsUTest.java
Allow to trigger link-respondent  (startAos event) from ServiceApplicationNotApproved
Fixes https://tools.hmcts.net/jira/browse/DIV-6531
> DIV-6531: Allow to trigger link-respondent from ServiceApplicationNotApproved

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/helper/GeneralEmailTaskHelper.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/helper/GeneralEmailTaskHelperTest.java
https://tools.hmcts.net/jira/browse/DIV-6502
This PR will make all docmosis template names for solicitors generic.
This moves away from "respondent solicitor name" to a "solicitor name"
> Remove specific solicitor names to be more generic

- build.gradle
Hopefully this will keep our tests working without the Java 11 error.
Existing tests
> Forcing dependencies to stop Java 11 issue

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/GetPetitionIssueFeesTest.java
I believe either some new constraint was introduced to disallow non-existent cases from being used in the "PreviousCaseId" or CCD AAT database was cleaned and the case we were using for this test no longer exist.
Either way, we're now testing this in a more reproducible approach.
> Fixing fees integration test

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/BasePayloadSpecificDocumentGenerationTask.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/generalorders/GeneralOrderDraftGenerationTask.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/generalorders/GeneralOrderGenerationTask.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/ServiceRefusalOrderGenerationTask.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/servicejourney/MakeServiceDecisionTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/generalorders/GeneralOrderGenerationTaskTest.java
https://tools.hmcts.net/jira/browse/DIV-6564 which is a subtask of https://tools.hmcts.net/jira/browse/DIV-6532
Updating naming convention for refusal file names to end with the current date it was created. This is following the model for general orders and also allows us to differentiate multiple deemed or dispensed documents in a service application collection.
> DIV-6564 Update current naming convention for service refusal documents

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/RetryRule.java
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/IntegrationTest.java
This change adds `RetryRule` to the `IntegrationTest` class to rerun flakey Functional API test-runs in AAT, to help improve build pipeline stability and reduce the impact from other services in the test environment. Max number of tries is set at 3 and has a cut-off at 30 retries, so that if a common component like IDAM is down it won't hog build resources retrying unnecessarily.
Fixes # (TA-138)
> feature(TA-138): Add test retries to the IntegrationTest class

- build.gradle
- dependency-check-suppressions.xml
Previously 1.2.1
https://tools.hmcts.net/jira/browse/DIV-6645
Add `servedByAlternativeMethod`
| Repo  | Link | Status | Issue
|-----|------|--------|-------|
| Comlib |https://github.com/hmcts/div-common-lib/pull/44      |    🟣Merged       |  |
| COS |https://github.com/hmcts/div-case-orchestration-service/pull/1164      |  🔴 Failed      |  CVE-2020-25638, CVE-2020-13956  |
| CDF |https://github.com/hmcts/div-case-data-formatter/pull/234      | 🔴 Failed       |   |
| CMS  | https://github.com/hmcts/div-case-maintenance-service/pull/379     |   🔴 Failed     |  |
> DIV-6545:Bump divCommonLib to 1.2.4

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/ServiceApplicationDataExtractor.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/common/Conditions.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/servicejourney/ServiceDecisionMadeWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/servicejourney/MakeServiceDecisionTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/servicejourney/ServiceDecisionMadeTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/ServiceApplicationDataExtractorTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/common/ConditionsTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/servicejourney/ServiceDecisionMadeWorkflowTest.java
Story:
https://tools.hmcts.net/jira/browse/DIV-6699
We have 2 callbacks:
```
{
"LiveFrom": "28/07/2020",
"CaseTypeID": "DIVORCE",
"ID": "makeServiceDecision",
"Name": "Make Service Decision",
"Description": "Make Service Decision",
"DisplayOrder": 12,
"PreConditionState(s)": "AwaitingServiceConsideration",
"PostConditionState": "*",
"CallBackURLAboutToSubmitEvent": "${CCD_DEF_COS_URL}/make-service-decision",
"RetriesTimeoutURLAboutToSubmitEvent": "30,30",
"CallBackURLSubmittedEvent": "${CCD_DEF_COS_URL}/service-decision-made/final",
"RetriesTimeoutURLSubmittedEvent": "120,120",
"SecurityClassification": "Public",
"ShowSummary":  "Y"
},
```
The first one is removing fields:
```
public class ServiceApplicationRemovalTask extends FieldsRemovalTask {
@Override
protected List<String> …
```
> DIV-6699: we must use values from last element of 'ServiceApplications' collection

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/PopulateDocLinkTask.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DecreeNisiAboutToBeGrantedWorkflow.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorDnFetchDocWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SolicitorDnFetchDocTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/PopulateDocLinkTaskTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DecreeNisiAboutToBeGrantedWorkflowTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorDnFetchDocWorkflowTest.java
https://tools.hmcts.net/jira/browse/DIV-6746
When a case has been `serviced by process server` or `alternative service method` there isn't a respondent answer document as part of the case data. When the Solicitor is drafting a DN the current flow presents the user with a screen with a link to this document for review. This change is to display a default message in these scenarios and also allows the flow to continue and not error out.
> DIV-6746: Updating existing workflow to cater for alternative service types

- build.gradle
On a fresh pull from github, i experienced consistent build failures that prevented COS from building and indexing appropriately. 
Following the approach detailed below:
https://docs.gradle.org/current/userguide/declaring_repositories.html
> BuildFix: Reorder mavenCentral and Jcenter

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/ccd/Organisation.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/ccd/OrganisationPolicy.java
Looking at the logs is seems there is more data returning than the domain model handles and getting errors when solicitorCreate event is triggered especially on Demo env
```
...ERROR [http-nio-4012-exec-4] u.g.h.r.l.f.RequestStatusLoggingFilter - Request POST /solicitor-create failed in 205ms
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalArgumentException: Unrecognized field "PreviousOrganisations" (class uk.gov.hmcts.reform.divorce.orchestration.domain.model.ccd.OrganisationPolicy), not marked as ignorable (3 known properties: "Organisation", "OrgPolicyReference", "OrgPolicyCaseAssignedRole"])
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: …
```
> Ignoring unknown fields

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorDnFetchDocWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SolicitorDnFetchDocTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorDnFetchDocWorkflowTest.java
Allow to proceed without respondent answers when bailiff is served successfully.
Fixes https://tools.hmcts.net/jira/browse/DIV-6089
Unit and functional tests
> DIV-6089: Allow to proceed without respondent answers when bailiff successful

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/common/Conditions.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackControllerTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/ConfirmSolDNReview.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java
Added new callback and logic
https://tools.hmcts.net/jira/browse/DIV-6533
ACs 1-3. (4 was previous implemented and tested)
- Respondent solicitor CAA is able to assign case to respondent solicitor. If a case is in the states 'AwaitingBailiffReferral', 'AwaitingBailifService', 'IssueToBailiff' then the CAA has access to these states and is able to assign the case to a member of their organisation.
- Respondent solicitor is able to draft an AOS response. If a case is in the states 'AwaitingBailiffReferral', 'AwaitingBailifService', 'IssueToBailiff' the respondent solicitor is able to trigger the event 'Draft AOS' (ID: SolicitorDraftAOS), however rather than moving into the state 'AOSdrafted' it stays in the same state.
- Respondent solicitor is able to update an AOS response. If a case is …
> Div-6533: RespSol complete AOS whilst bailiff in progress 

- build.gradle
- src/integrationTest/resources/fixtures/solicitor/solicitor-request-data.json
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/CcdFields.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RespondentOrganisationPolicyRemovalTask.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorCreateWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SolicitorCreateTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RespondentOrganisationPolicyRemovalTaskTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolicitorCreateWorkflowTest.java
Story:
https://tools.hmcts.net/jira/browse/DIV-6869
Make sure RespondentOrganisationPolicy is not populated when resp sol is not digital.
It may need this PR:
https://github.com/hmcts/div-ccd-definitions/pull/806
> DIV-6869: remove value from 'RespondentOrganisationPolicy' when resp sol not digital

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/SolicitorPersonalServiceCallbackTest.java
- src/integrationTest/resources/fixtures/issue-petition/solicitor-petition.json
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/SolicitorCallbackController.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/SolicitorService.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/SolicitorServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/BulkPrintWorkflow.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/IssuePersonalServicePackWorkflow.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolConfirmServiceWorkflow.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/ValidateForPersonalServicePackWorkflow.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/SolicitorCallbackControllerTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/BulkPrintTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SolicitorConfirmPersonalServiceTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/SolicitorServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/BulkPrintWorkflowTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/IssuePersonalServicePackWorkflowTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SolConfirmServiceWorkflowTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/ValidateForPersonalServicePackWorkflowTest.java
[Corresponding ccd-definitions PR](https://github.com/hmcts/div-ccd-definitions/pull/775)
- RPET-599 no div-cos changes required 
- RPET-567 update solConfirmPersonalService callback endpoint (#1158)
- RPET-269 remove generation of solicitor personal service letter (#1154)
[RPET-269](https://tools.hmcts.net/jira/browse/RPET-269)
[RPET-567](https://tools.hmcts.net/jira/browse/RPET-567)
[RPET-559](https://tools.hmcts.net/jira/browse/RPET-559)
Combined release PR for RPET-269, RPET-567, and RPET-559
> Release RPET-559, RPET-567, RPET-269

- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/dataextraction/DataExtractionEmailClientTest.java
This is not a test that we meant to run on Jenkins. If we want to run it locally we should add `@Test` annotation instead of removing `@Ignore`.
If it needs manual steps lets keep it clear.
> No more skipped unit tests

- dependency-check-suppressions.xml
- src/contractTest/resources/application.yml
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/maintenance/AosOverdueTest.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/aos/MarkCasesAsAosOverdueTask.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/DnDecisionMadeCallbackITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/aos/AosOverdueTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/aos/MarkCasesAsAosOverdueTaskTest.java
- src/test/resources/application.yml
We should use values from complex type stored in LAST_SERVICE_APPLICATION and not directly from field.
Field is cleaned up after the last event in multi-event-chain callback and it's moved to the last element of serviceApplications collections.
> fixed aos/make-overdue

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/bulk/scan/BulkScanIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/GetPetitionIssueFeesTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/SolicitorCreateAndUpdateTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cos/CosApiClient.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/OrganisationClient.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/PaymentClient.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/PbaValidationClient.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/config/SpecificHttpHeaders.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkCaseController.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkScanController.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/DecreeAbsoluteController.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationController.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/SolicitorCallbackController.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/internal/DecreeAbsoluteCaseInternalController.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/DocumentContentFetcherService.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/FetchPrintDocsFromDmStoreTask.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/MockedFunctionalTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/PaymentUpdateITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/ProcessPbaPaymentAbstractITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/ProcessPbaPaymentRepRespJourneyTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RetrievePbaNumbersITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/TransformationBulkScanITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/bulk/scan/UpdateBulkScanITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/callback/AosPackIssuedCallbackTest.java
Before I update the headers in `AssignCaseAccessClient` I want to clean up a bit.
Story:
https://tools.hmcts.net/jira/browse/RPET-984
Documentation:
https://tools.hmcts.net/confluence/display/ACA/API+Operation%3A+Assign+Access+within+Organisation
> RPET-984: Clean up headers const

- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/AddresseeDataExtractor.java
- src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/aos/AosOverdueCoverLetterGenerationTask.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/TestConstants.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/bulk/print/dataextractor/AddresseeDataExtractorTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/aos/AosOverdueCoverLetterGenerationTaskTest.java
- src/test/resources/jsonExamples/payloads/genericPetitionerData.json
Fix for issue where confidential petitioner's address details were still appearing on AOS overdue cover letters. Also fixes issue where, if a petitioner had legal representation, their own details were on the cover letter instead of their solicitor's.  
https://tools.hmcts.net/jira/browse/DFR-706
Unit tests to check that the address to appear on the cover letter matches what is expected, all unit tests passing. 
Manual test in preview, generated aosOverdue documents for confidential petitioner, and petitioner with solicitor scenarios, correct address is now …
> DFR-706 - rmv confidential petitioner details from AosOverdueCoverLetter

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/util/ResourceLoader.java
Fix: Java 8 date/time type `java.time.LocalDateTime` not supported by default
> fix jackson date time module in object mapper

- build.gradle
Bumping netty to 4.1.77
Fixes netty dependency fail
> Bumping netty
